// Generated by CoffeeScript 1.8.0

/**
DigiSeller shop widget v. 1.4.04
05.03.2015 http://artod.ru
 */

(function() {
  var DS, checkReady, _cssIsLoaded;

  if (window.DigiSeller != null) {
    return false;
  }

  _cssIsLoaded = true;

  DS = {};

  DS.el = {
    head: null,
    body: null
  };

  DS.opts = {
    seller_id: null,
    cart_uid: '',
    host: '//shop.digiseller.ru/xml/',
    hashPrefix: '#!digiseller',
    currency: 'RUR',
    currentLang: '',
    sort: 'name',
    rows: 10,
    view: 'list',
    main_view: 'tile',
    logo_img: '',
    menu_purchases: true,
    menu_reviews: true,
    menu_contacts: true,
    imgsize_firstpage: 160,
    imgsize_listpage: 162,
    imgsize_infopage: 163,
    imgsize_category: 200
  };

  DS.cookie = {
    get: function(name) {
      var matches = document.cookie.match(new RegExp(
		  "(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"
		));

		return matches ? decodeURIComponent(matches[1]) : undefined;
    },
    set: function(name, value, props) {
      props = props || {};

		var exp = props.expires;
		if (typeof exp === 'number' && exp) {
			var d = new Date();
			d.setTime(d.getTime() + exp * 1000);
			exp = props.expires = d;
		}

		if (exp && exp.toUTCString) {
			props.expires = exp.toUTCString();
		}

		value = DS.util.enc(value);

		var updatedCookie = name + '=' + value;
		for (var propName in props) {
			if ( !DS.util.hasOwnProp(props, propName) ) continue;

			updatedCookie += '; ' + propName;
			var propValue = props[propName];
			if (propValue !== true) {
				updatedCookie += '=' + propValue;
			}
		}

		document.cookie = updatedCookie;
    },
    del: function(name) {
      this.set(name, null, {
        expires: -1
      });
    }
  };

  DS.util = {
    getUID: (function() {
      var id;
      id = 1;
      return function() {
        return id++;
      };
    })(),
    enc: function(t) {
      return encodeURIComponent(t);
    },
    prevent: function(e) {
      if (e.preventDefault) {
        e.preventDefault();
      } else {
        e.returnValue = false;
      }
    },
    hasOwnProp: function(source, prop) {
      return Object.prototype.hasOwnProperty.call(source, prop);
    },
    extend: function(obj) {
      var type = typeof obj;
		if (! (type === 'function' || type === 'object' && !!obj) ) return obj;
		
		var /*source, */prop;
		//for (var i = 1, length = arguments.length; i < length; i++) {
		DS.util.each(arguments, function(source) {
			//source = arguments[i];
			for (prop in source)
				if ( DS.util.hasOwnProp(source, prop) )
					obj[prop] = source[prop];
			
		})
		//}
		return obj;
    },
    each: function(els, cb) {
      var el, i, _i, _len;
      for (i = _i = 0, _len = els.length; _i < _len; i = ++_i) {
        el = els[i];
        cb(el, i);
      }
    },
    getPopupParams: function(width, height) {
      var left, outerHeight, outerWidth, screenX, screenY, top;
      screenX = typeof window.screenX !== 'undefined' ? window.screenX : window.screenLeft;
      screenY = typeof window.screenY !== 'undefined' ? window.screenY : window.screenTop;
      outerWidth = typeof window.outerWidth !== 'undefined' ? window.outerWidth : document.body.clientWidth;
      outerHeight = typeof window.outerHeight !== 'undefined' ? window.outerHeight : document.body.clientHeight - 22;
      left = parseInt(screenX + ((outerWidth - width) / 2), 10);
      top = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
      return "scrollbars=1, resizable=1, menubar=0, left=" + left + ", top=" + top + ", width=" + width + ", height=" + height + ", toolbar=0, status=0";
    },
    getAbsPos: function(a) {
      var b = {
			x: 0,
			y: 0
		};
		if (a.offsetParent) do b.x += a.offsetLeft, b.y += a.offsetTop, a = a.offsetParent;
		while (a);
		return b;
    },
    scrollUp: function() {
      var body, doc, posY, scrollTop;
      doc = document.documentElement;
      body = document.body;
      scrollTop = doc && doc.scrollTop || body && body.scrollTop || 0;
      posY = DS.util.getAbsPos(DS.widget.main.$el).y;
      if (scrollTop > posY) {
        window.scroll(null, DS.util.getAbsPos(DS.widget.main.$el).y);
      }
    },
    debounce: function(cb, delay) {
      var timeout;
      timeout = null;
      return function() {
        var args, context;
        context = this;
        args = arguments;
        clearTimeout(timeout);
        timeout = setTimeout(function() {
          cb.apply(context, args);
          return context = args = null;
        }, delay || 200);
      };
    }
  };

  DS.$ = (function() {
    var _getVal, _klass, _setVal;
    _klass = function(action, el, cl) {
      var re;
      re = new RegExp('(^|\\s)' + (action === 'add' ? cl : cl.replace(' ', '|')) + '(\\s|$)', 'g');
      if (action === 'add' && re.test(el.className)) {
        return;
      }
      if (action === 'add') {
        el.className = (el.className + ' ' + cl).replace(/\s+/g, ' ').replace(/(^ | $)/g, '');
      } else {
        el.className = el.className.replace(re, "$1").replace(/\s+/g, ' ').replace(/(^ | $)/g, '');
      }
    };
    _getVal = function(el) {
      var option;
      if (!el || !el.nodeName) {
        return null;
      }
      switch (el.nodeName) {
        case 'SELECT':
          option = el.querySelectorAll('option')[el.selectedIndex];
          if (option) {
            return option.value;
          } else {
            return null;
          }
        default:
          return el.value;
      }
    };
    _setVal = function(el, val) {
      var options;
      if (!el || !el.nodeName) {
        return false;
      }
      switch (el.nodeName) {
        case 'SELECT':
          options = el.querySelectorAll('option');
          DS.util.each(options, function(option, i) {
            if (option.value === val + '') {
              el.selectedIndex = i;
            }
          });
          break;
        default:
          el.value = val;
          return;
      }
    };
    return function(selector, $context) {
      var context, out, _els;
      _els = [];
      if (typeof selector === 'string') {
        context = $context && $context.get && $context.get(0);
        if (typeof $context === 'undefined' || context) {
          DS.util.each((context || document).querySelectorAll(selector), function(el) {
            return _els.push(el);
          });
        }
      } else if (Object.prototype.toString.call(selector) === '[object Array]') {
        _els = selector;
      } else if (selector && (selector.nodeType || selector === window)) {
        _els = [selector];
      }
      out = {
        each: function(cb) {
          DS.util.each(_els, cb);
          return this;
        },
        addClass: function(cl) {
          this.each(function(el) {
            _klass('add', el, cl);
          });
          return this;
        },
        removeClass: function(cl) {
          this.each(function(el) {
            _klass('remove', el, cl);
          });
          return this;
        },
        on: function(type, handler) {
          this.each(function(el, i) {
            var events, ieHandler;
            if (!el.DigiSeller) {
              el.DigiSeller = {};
            }
            if (!el.DigiSeller.events) {
              el.DigiSeller.events = {};
            }
            if (!el.DigiSeller.events[type]) {
              el.DigiSeller.events[type] = [];
            }
            events = (el && el.DigiSeller && el.DigiSeller.events) || {};
            if (el.attachEvent) {
              ieHandler = function(type) {
                return handler.call(el, type);
              };
              el.attachEvent('on' + type, ieHandler);
              el.DigiSeller.events[type].push(ieHandler);
            } else if (el.addEventListener) {
              el.addEventListener(type, handler, false);
              el.DigiSeller.events[type].push(handler);
            }
          });
          return this;
        },
        off: function(type, handler) {
          this.each(function(el, i) {
            var handlers, j;
            handlers = (el && el.DigiSeller && el.DigiSeller.events && el.DigiSeller.events[type]) || [];
            j = handlers.length;
            while (j--) {
              handler = handlers[j];
              if (el.detachEvent) {
                el.detachEvent("on" + type, handler);
              } else if (el.removeEventListener) {
                el.removeEventListener(type, handler, false);
              }
              handlers.splice(j, 1);
            }
          });
          return this;
        },
        show: function() {
          return this.removeClass('digiseller-hidden');
        },
        hide: function() {
          return this.addClass('digiseller-hidden');
        },
        get: function(i) {
          return _els[i];
        },
        attr: function(attr, val) {
          var e;
          if (typeof val === 'undefined') {
            try {
              return _els[0] && _els[0].getAttribute(attr);
            } catch (_error) {
              e = _error;
              return null;
            }
          } else {
            this.each(function(el) {
              el.setAttribute(attr, val);
            });
          }
          return this;
        },
        html: function(html) {
          if (typeof html === 'undefined') {
            return _els[0] && _els[0].innerHTML;
          } else {
            this.each(function(el) {
              el.innerHTML = html;
            });
          }
          return this;
        },
        val: function(val) {
          if (typeof val === 'undefined') {
            return _els[0] && _getVal(_els[0]);
          } else {
            this.each(function(el) {
              _setVal(el, val);
            });
          }
          return this;
        },
        css: function(prop, val) {
          if (typeof val === 'undefined') {
            return _els[0] && _els[0].style[prop];
          } else {
            this.each(function(el) {
              el.style[prop] = val;
            });
          }
          return this;
        },
        remove: function() {
          this.each(function(el) {
            el.parentNode.removeChild(el);
          });
          return this;
        },
        parent: function() {
          var els;
          els = [];
          this.each(function(el) {
            els.push(el.parentNode);
          });
          return DS.$(els);
        },
        next: function() {
          var els;
          els = [];
          this.each(function(el) {
            els.push(el.nextSibling);
          });
          return DS.$(els);
        },
        prev: function() {
          var els;
          els = [];
          this.each(function(el) {
            els.push(el.prevSibling);
          });
          return DS.$(els);
        },
        children: function() {
          var els;
          els = [];
          this.each(function(el) {
            DS.util.each(el.children, function(child) {
              els.push(child);
            });
          });
          return DS.$(els);
        },
        eq: function(i) {
          return DS.$(_els[i]);
        }
      };
      out.length = _els.length;
      return out;
    };
  })();

  DS.dom = {
    getStyle: function(url, onLoad) {
      var link;
      link = document.createElement('link');
      link.type = 'text/css';
      link.rel = 'stylesheet';
      link.href = url;
      DS.el.head.appendChild(link);
    }
  };

  DS.serialize = function(form, onEach) {
    if (!form || form.nodeName !== "FORM") {
		return;
	}

	var i, j,
		obj = {};

	//for (i = form.elements.length - 1; i >= 0; i = i - 1) {
	DS.util.each(form.elements, function(element) {
		if (element.name === "") {
			//continue;
			return;
		}
		
		switch (element.nodeName) {
			case 'INPUT':
				switch (element.type) {
					case 'text':
					case 'hidden':
					case 'password':
					case 'number':
						obj[element.name] = DS.util.enc(element.value);
						break;
					case 'checkbox':
					case 'radio':
						if (element.checked) {
							obj[element.name] = DS.util.enc(element.value);
						}
						break;
					case 'file':
						break;
				}
				break;
			case 'TEXTAREA':
				obj[element.name] = DS.util.enc(element.value);
				break;
			case 'SELECT':
				switch (element.type) {
					case 'select-one':
						obj[element.name] = DS.util.enc(element.value);
						break;
					case 'select-multiple':
						//for (j = element.options.length - 1; j >= 0; j = j - 1) {
						DS.util.each(element.options, function(option) {
							if (option.selected) {
								obj[element.name] = DS.util.enc(option.value);
							}
						});
						break;
				}
				break;
		}
		
		if (typeof onEach === 'function') {
			onEach(element);
		}
	});

	return obj;
  };

  DS.historyClick = (function() {
	var _rootAlias = '',
		_needReload = false,
		_routes = [],
		_revRoutes = [];

	function init() {
		if (historyClick.interval) {
			return;
		}

		DS.$(window).on('hashchange', urlHashCheck);
	}

	function urlHashCheck() {
		var mayChangeReload = false; // _needReload может обнулиться так как urlHashCheck может еще не закончиться а _needReload уже поставили true

		if (_needReload) {
			mayChangeReload = true;
		}

		if (window.location.hash !== historyClick.currentHash || _needReload) {
			historyClick.prevHash = ( _needReload ? historyClick.prevHash : historyClick.currentHash );
			historyClick.currentHash = window.location.hash.toString();

			go(historyClick.currentHash && historyClick.currentHash != '#' ? historyClick.currentHash : _rootAlias);

			if (mayChangeReload) {
				_needReload = false;
			}
		}
	}

	function go(hash) {
		if (!hash) {
			return;
		}
		
		historyClick.onGo()

		var pattern,
			callback;

		for (var i = 0, len = _revRoutes.length; i < len; i++) {
			pattern = _revRoutes[i][0];
			callback = _revRoutes[i][1];

			if (pattern.test(hash) && typeof callback === 'function') {
				historyClick.params = hash.match(pattern);
				callback(historyClick.params);

				return;
			}
		}
	}

	var historyClick = {
		interval: null,
		currentHash: '',
		prevHash: '',
		params: [],
		start: function() {
			init();
			urlHashCheck();
		},
		rootAlias: function(hash) {
			if (hash) {
				_rootAlias = hash;
			} else {
				return _rootAlias;
			}
		},
		addRoute: function(pattern, callback) {
			if (typeof pattern === 'string') {
				pattern = [pattern];
			}

			for (var i = 0; i < pattern.length; i++) {
				_routes.push([new RegExp(pattern[i], 'i'), callback]);
			}

			_revRoutes = _routes.slice().reverse(); // клонируем и реверсируем
		},
		reload: function() {
			_needReload = true;
			urlHashCheck();
		},
		changeHashSilent: function(hash) {
			historyClick.prevHash = historyClick.currentHash;
			historyClick.currentHash = window.location.hash = hash;
		},
		onGo: function() {
		
		}
	};

	return historyClick;
})();

  DS.ajax = (function() {
    var _isXdr = false,
		createCORSRequest = function() {
			return null;
		};	
	
	if ( 'withCredentials' in new XMLHttpRequest() ) {
		createCORSRequest = function(method, url) {
			var xhr = new XMLHttpRequest();
			xhr.open(method, url, true);
			if (method === 'POST') xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded; charset=UTF-8');
			return xhr;
		}
	} else if (typeof XDomainRequest !== 'undefined') {
		_isXdr = true;
		createCORSRequest = function(method, url) {
			var xdr = new XDomainRequest();
			xdr.open(method, url);
			
			return xdr;
		}
	}
	
	/*function createCORSRequest(method, url) {
		var xhr = new XMLHttpRequest();
		if ('withCredentials' in xhr) {
			xhr.open(method, url, true);
		} else if (typeof XDomainRequest !== 'undefined') {
			xhr = new XDomainRequest();
			xhr.open(method, url);
		} else {
			xhr = null;
		}
		
		if (xhr && xhr.setRequestHeader && method === 'POST')
			xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded; charset=UTF-8');
		
		return xhr;
	}*/
	
	function toQueryString(params) {
		var key,
			queryString = [];

		for (key in params) {
			if ( !DS.util.hasOwnProp(params, key) ) continue;
			
			queryString.push( ( DS.util.enc(key) + '=' + DS.util.enc(params[key]) ) );
		}

		return queryString.join('&');
	};
    return function(method, url, opts) {
      var needCheck, queryString, sign, uid, xhr, _onComplete;
      opts = DS.util.extend({
        $el: null,
        data: {},
        onLoad: function() {},
        onFail: function() {},
        onComplete: function() {}
      }, opts);
      if (_isXdr && method === 'POST') {
        method = 'GET';
        opts.data && (opts.data.xdr = 1);
      }
      sign = (/\?/.test(url) ? '&' : '?');
      queryString = toQueryString(opts.data);
      xhr = createCORSRequest(method, url + sign + 'transp=cors&format=json&lang=' + DS.opts.currentLang + (method === 'GET' ? '&_=' + Math.random() + (queryString ? '&' + queryString : '') : ''));
      uid = DS.util.getUID();
      DS.widget.loader.show(uid);
      _onComplete = function(xhr) {
        opts.onComplete(xhr);
        return DS.widget.loader.hide(uid);
      };
      if (!xhr) {
        return;
      }
      needCheck = opts.$el ? true : false;
      if (needCheck) {
        opts.$el.attr('data-qid', uid);
      }
      xhr.onload = function() {
        _onComplete(xhr);
        if (needCheck && parseInt(opts.$el.attr('data-qid')) !== uid) {
          return;
        }
        return opts.onLoad(JSON.parse(xhr.responseText), xhr);
      };
      xhr.onerror = function() {
        _onComplete(xhr);
        return opts.onFail(xhr);
      };
      xhr.onabort = function() {
        console.log('abort');
        return _onComplete(xhr);
      };
      if (_isXdr) {
        setTimeout(function() {
          xhr.send(queryString);
        }, 0);
      } else {
        xhr.send(queryString);
      }
      return xhr;
    };
  })();


  /*
  DS.JSONP = `(function() {
  	var _callbacks = [];
  
  	function jsonp(url, $el, params, onLoad, onFail, onComplete) {
  		var query = (url || '').indexOf('?') === -1 ? '?' : '&',
  			key;
  
  		params = params || {};
  
  		var _uid = DS.util.getUID();
  		params.queryId = _uid;
  
  		for (key in params) {
  			if ( !DS.util.hasOwnProp(params, key) ) continue;
  
  			query += DS.util.enc(key) + '=' + DS.util.enc(params[key]) + '&'
  		}
  
  		var needCheck = $el ? true : false;
  
  		if (needCheck) {
  			$el.attr('data-qid', _uid);
  		}
  
  		_callbacks[_uid] = function(data) {
  			if ( needCheck && ( !$el || data.queryId != $el.attr('data-qid') ) ) {
  				return;
  			}
  
  			onLoad(data);
  		};
  
  		DS.dom.getScript(url + query + '_' + Math.random(), null, onFail, onComplete);
  
  		return _uid;
  	}
  
  	return {
  		get: jsonp,
  		callback: function(data) {
  			if (!data || !data.queryId || !_callbacks[data.queryId]) {
  				return;
  			}
  
  			_callbacks[data.queryId](data);
  
  			try {
  				delete _callbacks[data.queryId];
  			} catch (e) {}
  
  			_callbacks[data.queryId] = null;
  		}
  	};
  })()`
   */

  DS.tmpl = function(text, data) {
	settings = {
		evaluate		: /<\?([\s\S]+?)\?>/g,
		interpolate : /<\?=([\s\S]+?)\?>/g,
		escape			: /<\?-([\s\S]+?)\?>/g
	};

	// Combine delimiters into one regular expression via alternation.
	var noMatch = /(.)^/;
	var matcher = new RegExp([
		(settings.escape || noMatch).source,
		(settings.interpolate || noMatch).source,
		(settings.evaluate || noMatch).source
	].join('|') + '|$', 'g');

	// Compile the template source, escaping string literals appropriately.
	var index = 0,
		source = "__p+='",
		escaper = /\\|'|\r|\n|\t|\u2028|\u2029/g,
		escapes = {
			"'":			"'",
			'\\':		 '\\',
			'\r':		 'r',
			'\n':		 'n',
			'\t':		 't',
			'\u2028': 'u2028',
			'\u2029': 'u2029'
		};

	text.replace(matcher, function(match, escape, interpolate, evaluate, offset) {
		source += text.slice(index, offset)
			.replace(escaper, function(match) {
				return '\\' + escapes[match];
			});

		/* todo: _.escape переделать */
		source +=
			escape ? "'+\n((__t=(" + escape + "))==null?'':_.escape(__t))+\n'" :
			interpolate ? "'+\n((__t=(" + interpolate + "))==null?'':__t)+\n'" :
			evaluate ? "';\n" + evaluate + "\n__p+='" : '';

		index = offset + match.length;
	});

	source += "';\n";

	// If a variable is not specified, place data values in local scope.
	if (!settings.variable) {
		source = 'with(obj||{}){\n' + source + '}\n';
	}

	source = "var __t,__p='',__j=Array.prototype.join," +
		"print=function(){__p+=__j.call(arguments,'');};\n" +
		source + "return __p;\n";

	try {
		var render = new Function(settings.variable || 'obj', 'DS', source);
	} catch (e) {
		e.source = source;
		throw e;
	}

	if (data) {
		return render(data, DS);
	}

	var template = function(data) {
		return render.call(this, data, DS);
	};

	// Provide the compiled function source as a convenience for precompilation.
	template.source = 'function(' + (settings.variable || 'obj') + '){\n' + source + '}';

	return template;
};

  DS.popup = (function() {
    var close, img, init, isClosed, isCompV, prefix, resize, setup, show;
    setup = {};
    img = null;
    prefix = 'digiseller-popup-';
    isCompV = document.compatMode === 'CSS1Compat';
    isClosed = true;
    show = function(onResize) {
      setup.$loader.hide();
      setup.$container.show();
      DS.$(window).on('resize', onResize);
      onResize();
    };
    close = function(e) {
      if (isClosed) {
        return;
      }
      if (e) {
        DS.util.prevent(e);
      }
      setup.$img.html('');
      setup.$main.hide();
      DS.$(window).off('resize');
      isClosed = true;
      img = null;
    };
    resize = function(h, w, isHard) {
      var body, doc, h1, hs, isDec, scale0, topScroll, w1, wih, wiw, ws;
      wih = window.innerHeight;
      hs = (typeof wih !== 'undefined' ? wih : document[isCompV ? 'documentElement' : 'body'].offsetHeight - 22) - 100;
      if (!isHard) {
        scale0 = h / w;
        wiw = window.innerWidth;
        ws = (typeof wiw !== 'undefined' ? wiw : document[isCompV ? 'documentElement' : 'body'].offsetWidth) - 120;
        h1 = hs;
        w1 = ws;
        isDec = false;
        h >= hs && (isDec = true) || (h1 = h);
        w >= ws && (isDec = true) || (w1 = w);
        if (isDec) {
          if (scale0 <= h1 / w1) {
            h1 = Math.round(scale0 * w1);
          } else {
            w1 = Math.round(h1 / scale0);
          }
        }
        img.style.height = h1 + 'px';
        img.style.width = w1 + 'px';
      }
      setup.$container.css('width', ((isHard ? w : w1) + 50) + 'px');
      doc = document.documentElement;
      body = document.body;
      topScroll = doc && doc.scrollTop || body && body.scrollTop || 0;
      setup.$container.css('top', (hs - (isHard ? h : h1) + 20) / 3 + topScroll + 'px');
    };
    init = function() {
      var container;
      container = document.createElement('div');
      container.innerHTML = DS.tmpl(DS.tmpls.popup, {
        p: prefix
      });
      DS.el.body.appendChild(container.firstChild);
      DS.util.each(['main', 'fade', 'loader', 'container', 'close', 'img', 'left', 'right'], function(param) {
        setup['$' + param] = DS.$("#" + prefix + param);
      });
      setup.$fade.on('click', close);
      setup.$close.on('click', close);
    };
    return {
      open: function(type, id, onLeft, onRight) {
        !setup.$main && init();
        isClosed = false;
        setup.$container.hide();
        setup.$main.show();
        setup.$loader.show();
        setup.$left[onLeft ? 'show' : 'hide']();
        if (onLeft) {
          setup.$left.off('click').on('click', onLeft);
        }
        setup.$right[onRight ? 'show' : 'hide']();
        if (onRight) {
          setup.$right.off('click').on('click', onRight);
        }
        switch (type) {
          case 'img':
            setup.$img.removeClass('digiseller-popup-video');
            img = new Image();
            img.onload = function() {
              var h, w;
              if (isClosed) {
                return;
              }
              h = img.height;
              w = img.width;
              DS.$(window).off('resize');
              show(function() {
                resize(h, w);
              });
              return setup.$img.html('').get(0).appendChild(img);
            };
            img.src = id;
            break;
          default:
            setup.$img.addClass('digiseller-popup-video');
            show(function() {
              resize(200, 500, true);
            });
            setup.$img.html(id);
        }
      },
      close: close
    };
  })();

  DS.share = {
    vk: function(title, img) {
      return '//vkontakte.ru/share.php?' + 'url=' + DS.util.enc(document.location) + '&' + 'title=' + DS.util.enc(title) + '&' + 'image=' + DS.util.enc(img) + '&' + 'noparse=true';
    },
    tw: function(title) {
      return '//twitter.com/share?' + 'text=' + DS.util.enc(title) + '&' + 'url=' + DS.util.enc(document.location);
    },
    fb: function(title, img) {
      return '//www.facebook.com/sharer.php?u=' + DS.util.enc(document.location);
    },
    wme: function(title, img) {
      return '//events.webmoney.ru/sharer.aspx?' + 'url=' + DS.util.enc(document.location) + '&' + 'title=' + DS.util.enc(title) + '&' + 'image=' + DS.util.enc(img) + '&' + 'noparse=0';
    }
  };

  DS.agree = function(flag, onAgree) {
    var $rules;
    $rules = DS.$('#digiseller-calc-rules');
    if ($rules.length) {
      $rules.get(0).checked = flag;
    }
    DS.opts.agree = flag ? 1 : 0;
    DS.cookie.set('digiseller-agree', DS.opts.agree);
    DS.popup.close();
    if (onAgree) {
      onAgree();
    }
  };

  DS.widget = {
    main: {
      $el: null,
      init: function() {
        var callback;
        this.$el = DS.$('#digiseller-main');
        this.$el.html('').on('click', function(e) {
          callback(e, 'click');
        });
        callback = function(e, type) {
          var $el, action;
          $el = DS.$(e.originalTarget || e.srcElement);
          action = $el.attr('data-action');
          if (action && typeof DS.eventsDisp[type + '-' + action] === 'function') {
            return DS.eventsDisp[type + '-' + action]($el, e);
          }
        };
      }
    },
    loader: (function() {
      var _counter, _timeouts;
      _counter = 0;
      _timeouts = [];
      return {
        $el: null,
        init: function() {
          var div;
          div = document.createElement('div');
          div.id = 'digiseller-loader';
          div.className = div.id;
          div.innerHTML = DS.tmpl(DS.tmpls.loader, {});
          DS.el.body.appendChild(div);
          this.$el = DS.$("#" + div.id).hide();
        },
        show: function(uid) {
          var that;
          that = this;
          _timeouts[uid] = setTimeout(function() {
            _timeouts[uid] = 0;
            _counter++;
            that.$el.show();
          }, 1000);
        },
        hide: function(uid) {
          clearTimeout(_timeouts[uid]);
          if (_timeouts[uid] === 0) {
            _counter--;
          }
          delete _timeouts[uid];
          if (_counter <= 0) {
            this.$el.hide();
          }
        }
      };
    })(),
    search: {
      $el: null,
      $input: null,
      prefix: 'digiseller-search',
      init: function() {
        var $form, that;
        this.$el = DS.$("#" + this.prefix);
        if (!this.$el.length) {
          return;
        }
        this.$el.html(DS.tmpls.search);
        this.$input = DS.$("input." + this.prefix + "-input", this.$el);
        $form = DS.$("form." + this.prefix + "-form", this.$el);
        that = this;
        $form.on('submit', function(e) {
          DS.util.prevent(e);
          window.location.hash = DS.opts.hashPrefix + ("/search?s=" + (that.$input.val()));
        });
      }
    },
    lang: {
      $el: null,
      prefix: 'digiseller-langs',
      init: function() {
        this.$el = DS.$("#" + this.prefix);
        if (!this.$el.length) {
          return;
        }
        this.$el.html(DS.tmpl(DS.tmpls.langs, {}));
        DS.$('a', this.$el).on('click', function(e) {
          var lang;
          DS.util.prevent(e);
          lang = DS.$(this).attr('data-lang');
          DS.cookie.set('digiseller-lang', lang);
          DS.opts.currentLang = lang;
          window.location.reload();
        });
      }
    },
    category: {
      $el: null,
      isInited: false,
      prefix: 'digiseller-category',
      init: function() {
        var that;
        this.$el = DS.$("#" + this.prefix);
        if (!this.$el.length) {
          return;
        }
        this.isInited = false;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_categories.asp', {
          $el: this.$el,
          data: {
            seller_id: DS.opts.seller_id
          },
          onLoad: function(res) {
            if (!res) {
              return false;
            }
            that.$el.html(that.render(res.category, null, 0));
            that.isInited = true;
            that.mark();
          }
        });
      },
      mark: (function() {
        var _go;
        _go = function(cid) {
          var $ancestor, $cat, $cats, $parent, $subs;
          $cats = DS.$('li', this.$el);
          if (!$cats.length) {
            return;
          }
          $subs = DS.$('ul', this.$el);
          $subs.hide();
          $subs.eq(0).show();
          $cats.removeClass(this.prefix + '-active').removeClass(this.prefix + '-active-hmenu');
          if (!cid) {
            return;
          }
          $cat = DS.$("#" + this.prefix + "-" + cid);
          if (!$cat.length) {
            return;
          }
          $cat.addClass(this.prefix + '-active');
          $parent = $ancestor = $cat;
          while ($parent.get(0).id !== this.prefix) {
            $parent.show();
            $parent = $parent.parent();
            if (/li/i.test($parent.get(0).nodeName)) {
              $parent.addClass(this.prefix + '-active-hmenu');
            }
          }
          DS.$("#" + this.prefix + "-sub-" + cid).show();
        };
        return function(cid) {
          var count, interval, that;
          if (!this.$el || !this.$el.length) {
            return;
          }
          if (this.isInited) {
            _go.call(this, cid);
          } else {
            that = this;
            count = 0;
            interval = setInterval(function() {
              if (that.isInited || count > 1000) {
                clearInterval(interval);
                if (that.isInited) {
                  _go.call(that, cid);
                }
              }
              count++;
            }, 50);
          }
        };
      })(),
      render: function(categories, parent_cid) {
        var out, that, tmpl;
        if (!categories) {
          return '';
        }
        out = '';
        tmpl = DS.tmpl(DS.tmpls.category);
        that = this;
        DS.util.each(categories, function(category) {
          out += tmpl({
            d: category,
            url: DS.opts.hashPrefix + ("/articles/" + category.id),
            id: that.prefix + ("-" + category.id),
            sub: that.render(category.sub, category.id)
          });
        });
        return DS.tmpl(DS.tmpls.categories, {
          id: parent_cid ? this.prefix + ("-sub-" + parent_cid) : '',
          out: out
        });
      }
    },
    currency: {
      $el: null,
      init: function() {
        var $select;
        this.$el = DS.$('#digiseller-currency');
        if (!this.$el.length) {
          return;
        }
        this.$el.html(DS.tmpl(DS.tmpls.currency, {}));
        $select = DS.$('select', this.$el);
        $select.val(DS.opts.currency).on('change', function(e) {
          var $this, type;
          $this = DS.$(this);
          type = $this.attr('data-type');
          DS.opts.currency = $select.val();
          DS.cookie.set('digiseller-currency', DS.opts.currency);
          DS.historyClick.reload();
        });
      }
    },
    pager: (function() {
      function _Class($el, opts) {
        this.$el = $el;
        opts = opts || {};
        this.page = opts.page || 1;
        this.rows = opts.rows || 10;
        this.total = opts.total || 0;
        this.opts = {
          tmpl: opts.tmpl || DS.tmpls.pages,
          max: opts.max || 2,
          getLink: opts.getLink || function(page) {
            return page;
          },
          onChangeRows: opts.onChangeRows || function(rows) {}
        };
        return;
      }

      _Class.prototype.mark = function() {
        var $pages, that;
        $pages = DS.$('a', this.$el);
        that = this;
        $pages.each(function(el) {
          var $page;
          $page = DS.$(el);
          $page[that.page === parseInt($page.attr('data-page')) ? 'addClass' : 'removeClass']('digiseller-activepage');
        });
        return this;
      };

      _Class.prototype.render = function() {
        var left, out, page, right, that;
        this.page = parseInt(this.page);
        this.rows = parseInt(this.rows);
        this.total = parseInt(this.total);
        this.$el[this.total ? 'show' : 'hide']();
        out = '';
        if (this.total > 1) {
          left = this.page - this.opts.max;
          left = left < 1 ? 1 : left;
          right = this.page + this.opts.max;
          right = right > this.total ? this.total : right;
          page = left;
          while (page <= right) {
            out += this.opts.getLink(page);
            page++;
          }
          if (left > 1) {
            out = this.opts.getLink(1) + (left > 2 ? '<span>...</span> ' : '') + out;
          }
          if (right < this.total) {
            out = out + (right < this.total - 1 ? '<span>...</span> ' : '') + this.opts.getLink(this.total);
          }
        }
        this.$el.html(DS.tmpl(this.opts.tmpl, {
          out: out
        }));
        that = this;
        DS.$('select', this.$el).val(this.rows).on('change', function(e) {
          var $this;
          $this = DS.$(this);
          that.rows = $this.val();
          that.opts.onChangeRows(that.rows);
        });
        this.mark();
        return this;
      };

      return _Class;

    })(),
    comments: (function() {
      function _Class($el, product_id, init) {
        this.$el = $el;
        this.product_id = product_id;
        this.init = init;
        this.isInited = false;
        this.type = '';
        this.page = 1;
        this.rows = 10;
        this.pager = null;
        return;
      }

      _Class.prototype.get = function() {
        var that;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_reviews.asp', {
          $el: this.$el,
          data: {
            seller_id: DS.opts.seller_id,
            product_id: this.product_id,
            type: this.type,
            page: this.page,
            rows: this.rows
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          }
        });
      };

      _Class.prototype.render = function(data) {
        var comments, out, tmpl;
        comments = data.review;
        out = '';
        if (!comments) {
          out = DS.tmpl(DS.tmpls.nothing, {});
        } else {
          tmpl = DS.tmpl(DS.tmpls.comment);
          DS.util.each(comments, function(comment) {
            out += tmpl({
              d: comment
            });
          });
        }
        if (this.isInited) {
          DS.util.extend(this.pager, {
            page: this.page,
            rows: this.rows,
            total: data.totalPages
          });
          this.pager.render();
        } else {
          this.init(data);
          this.container = DS.$('.digiseller-comments', this.$el);
          this.isInited = true;
        }
        this.container.html(out);
      };

      return _Class;

    })(),
    calc: (function() {
      var _els, _prefix;

      _els = ['amount', 'cnt', 'cntSelect', 'currency', 'amountR', 'price', 'buy', 'limit', 'rules', 'cart', 'method', 'curadd'];

      _prefix = 'digiseller-calc';

      function _Class(id) {
        var $curAddSelects, $currencyOpts, $optionsCont, $parentRules, debouncedGet, onChangeCurAdd, onChangeCurrency, rules, that;
        this.id = id;
        this.$ = {
          container: DS.$("#" + _prefix)
        };
        if (!this.$.container.length) {
          return;
        }
        that = this;
        DS.util.each(_els, function(el) {
          that.$[el] = DS.$("#" + _prefix + "-" + el);
        });
        debouncedGet = DS.util.debounce(function(type) {
          that.get(type);
        });
        if (this.$.amount.length) {
          if (this.$.cnt.length) {
            this.$.amount.on('keyup', function() {
              debouncedGet('amount');
            });
            this.$.cnt.on('keyup', function() {
              debouncedGet('cnt');
            });
          }
          this.$.cntSelect.on('change', function() {
            that.get('cnt');
          });
        }
        onChangeCurrency = function(withoutGet) {
          var $curAdd, index, vars;
          index = that.$.currency.get(0).selectedIndex;
          $curAdd = $curAddSelects.eq(index);
          vars = parseInt($curAdd.attr('data-vars'));
          $curAddSelects.hide();
          if (vars > 1) {
            $curAdd.show();
            that.$.method.removeClass(_prefix + '-method').addClass(_prefix + '-method-two');
          } else {
            that.$.method.addClass(_prefix + '-method').removeClass(_prefix + '-method-two');
          }
          return onChangeCurAdd($curAdd, withoutGet);
        };
        $currencyOpts = DS.$('option', this.$.currency);
        onChangeCurAdd = function($this, withoutGet) {
          var index, val;
          index = $this.attr('data-index');
          val = $this.val();
          that.$.currency.get(0).selectedIndex = index;
          $currencyOpts.eq(index).val(val);
          if (!withoutGet) {
            that.get();
          }
        };
        $curAddSelects = DS.$('select', this.$.curadd);
        $curAddSelects.on('change', function() {
          return onChangeCurAdd(DS.$(this));
        });
        this.$.currency.on('change', function() {
          return onChangeCurrency();
        });
        onChangeCurrency(true);
        $optionsCont = DS.$('#digiseller-calc-options');
        if ($optionsCont.length) {
          this.$.options = DS.$('input[type="radio"], input[type="checkbox"], select', $optionsCont);
          this.$.options.on('change', function() {
            that.get();
          });
        }
        this.get();
        if (that.$.rules.length) {
          $parentRules = that.$.rules.parent();
          rules = function(flag) {
            return $parentRules[flag && !that.$.rules.get(0).checked ? 'addClass' : 'removeClass'](_prefix + '-confirmation-error');
          };
          this.$.buy.on('mouseover', function() {
            rules(true);
          }).on('mouseout', function() {
            rules(false);
          });
          this.$.cart.on('mouseover', function() {
            rules(true);
          }).on('mouseout', function() {
            rules(false);
          });
        }
        return;
      }

      _Class.prototype.get = function(type) {
        var params, that;
        that = this;
        params = {
          p: this.id
        };
        if (type === 'amount') {
          params.a = this.$.amount.val();
        } else {
          params.n = this.$.cntSelect.length ? this.$.cntSelect.val() : this.$.cnt.val() || 0;
          this.checkMinMax(params.n);
        }
        params.c = this.$.currency.val();
        params.x = '<response>';
        if (this.$.options) {
          this.$.options.each(function(el) {
            switch (el.nodeName) {
              case 'SELECT':
                params.x += '<option O="' + el.name.replace('option_select_', '') + '" V="' + DS.$(el).val() + '"/>';
                break;
              default:
                if (el.checked) {
                  params.x += '<option O="' + el.name.replace('option_checkbox_', '').replace('option_radio_', '') + '" V="' + DS.$(el).val() + '"/>';
                }
            }
          });
        }
        params.x += '</response>';
        DS.ajax('GET', '//www.oplata.info/asp2/price_options.asp', {
          $el: this.$.container,
          data: params,
          onLoad: function(res) {
            if (!res) {
              return false;
            }
            that.render(res);
          }
        });
      };

      _Class.prototype.checkMinMax = function(cnt) {
        var max, min, minmax, that;
        that = this;
        cnt = parseInt(cnt);
        max = parseInt(this.$.buy.attr('data-max'));
        min = parseInt(this.$.buy.attr('data-min'));
        minmax = function(val, flag) {
          that.disable(true);
          that.$.limit.html(DS.tmpl(DS.tmpls.minmax, {
            val: val,
            flag: flag
          })).show();
        };
        if (max && cnt > max) {
          minmax(max, true);
          return;
        } else if (min && cnt < min) {
          minmax(min, false);
          return;
        }
        this.disable(false);
        this.$.limit.hide();
      };

      _Class.prototype.render = function(data) {
        if (!data) {
          return false;
        }
        this.$.amount.val(data.amount);
        this.$.price.html(data.amount + ' ' + data.curr);
        if (this.$.cnt.length && data.cnt) {
          this.checkMinMax(data.cnt);
          this.$.cnt.val(data.cnt);
        }
        if (this.$.cntSelect.length && data.curr) {
          this.$.cntSelect.val(data.curr);
        }
        this.$.amountR.html(data.curr);
        if (data.amount === '0') {
          this.disable(true);
        }
      };

      _Class.prototype.disable = function(disabled) {
        var go;
        go = function($el) {
          return $el[disabled ? 'addClass' : 'removeClass']('digiseller-cart-btn-disabled').attr('data-action', disabled ? '' : 'buy');
        };
        go(this.$.buy);
        go(this.$.cart);
      };

      return _Class;

    })(),
    cartButton: {
      $el: null,
      prefix: 'digiseller-cart',
      init: function() {
        this.$el = DS.$("#" + this.prefix + "-btn");
        if (!this.$el.length) {
          return;
        }
        DS.opts.hasCart = true;
        this.$el.html(DS.tmpl(DS.tmpls.cartButton, {
          count: DS.opts.cart_cnt
        }));
        DS.$('a', this.$el).on('click', function(e) {
          DS.util.prevent(e);
          new DS.widget.cart();
        });
      },
      setCount: function(count) {
        DS.$("#" + this.prefix + "-count").html(count);
        DS.$("#" + this.prefix + "-empty")[count ? 'removeClass' : 'addClass'](this.prefix + '-btn-empty');
      }
    },
    cart: (function() {
      var _prefix;

      _prefix = 'digiseller-cart';

      function _Class(currency) {
        this.currency = currency;
        this.get();
      }

      _Class.prototype.get = function() {
        var that;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_cart_lst.asp', {
          $el: DS.widget.cartButton.$el,
          data: {
            cart_uid: DS.opts.cart_uid,
            cart_curr: this.currency || ''
          },
          onLoad: function(res) {
            if (!res) {
              return false;
            }
            that.render(res);
          }
        });
      };

      _Class.prototype.render = function(res) {
        var count, items, tmpl;
        items = '';
        tmpl = DS.tmpl(DS.tmpls.cartItem);
        count = 0;
        if (res.products) {
          DS.util.each(res.products, function(product, i) {
            count++;
            items += tmpl({
              d: product,
              even: !!(i % 2)
            });
          });
        }
        DS.widget.cartButton.setCount(count);
        DS.popup.open('text', DS.tmpl(DS.tmpls.cart, {
          d: res,
          failPage: DS.util.enc(window.location),
          items: items
        }));
        this.init(res);
      };

      _Class.prototype.init = function(res) {
        var $context, $select, changeCount, that;
        $context = DS.$("#" + _prefix + "-items");
        if (!$context.length) {
          return;
        }
        that = this;
        changeCount = DS.util.debounce(function($this, isDel) {
          that.changeCount($this, isDel);
        });
        DS.$("." + _prefix + "-del-product", $context).on('click', function(e) {
          DS.util.prevent(e);
          that.changeCount(DS.$(this), true);
        });
        DS.$('input', $context).on('change', function(e) {
          changeCount(DS.$(this));
        }).on('keyup', function(e) {
          changeCount(DS.$(this));
        });
        DS.$("." + _prefix + "-params-toggle", $context).on('click', function(e) {
          var $el, isOpened;
          DS.util.prevent(e);
          $el = DS.$(this.parentNode);
          isOpened = $el.attr('data-opened') === '1';
          $el[isOpened ? 'removeClass' : 'addClass'](_prefix + '-show-params').attr('data-opened', isOpened ? 0 : 1);
        });
        $select = DS.$("#" + _prefix + "-currency");
        $select.val(res.currency).on('change', function(e) {
          new DS.widget.cart($select.val());
        });
        this.$go = DS.$("#" + _prefix + "-go");
        this.$go.on('click', function(e) {
          DS.util.prevent(e);
          if (that.$go.attr('data-disabled') === '1') {
            return;
          }
          this.parentNode.submit();
        });
        this.$amount = DS.$("#" + _prefix + "-amount");
        this.$amountCont = DS.$("#" + _prefix + "-amount-cont");
      };

      _Class.prototype.update = function(res, id) {
        var count, hasError, idForDel, items;
        items = (res && res.products ? res.products : []);
        idForDel = id;
        this.$amount.html(res.amount);
        hasError = false;
        count = 0;
        if (!items.length) {
          this.disable(true);
        } else {
          DS.util.each(items, function(item, i) {
            var $error, $item;
            count++;
            if (item.id === id) {
              idForDel = false;
            }
            $item = DS.$("#" + _prefix + "-item-" + item.id);
            $error = DS.$("#" + _prefix + "-item-error-" + item.id);
            if (item.error) {
              $item.addClass(_prefix + '-error');
              $item.attr('data-error', 1);
              $error.show();
              DS.$('td', $error).html(item.error);
            } else if (item.id === id) {
              $item.removeClass(_prefix + '-error');
              $item.attr('data-error', 0);
              $error.hide();
            }
            if ($item.attr('data-error') === '1') {
              hasError = true;
            }
          });
          this.disable(hasError);
        }
        DS.widget.cartButton.setCount(count);
        if (idForDel) {
          DS.$("#" + _prefix + "-item-" + idForDel).remove();
          DS.$("#" + _prefix + "-item-error-" + idForDel).remove();
        }
      };

      _Class.prototype.disable = function(disable) {
        this.$go[disable ? 'addClass' : 'removeClass'](_prefix + '-btn-disabled').attr('data-disabled', disable ? '1' : '0');
        this.$amountCont[disable ? 'hide' : 'show']();
      };

      _Class.prototype.changeCount = function($this, isDel) {
        var $count, $item, count, id, newCount, parsedCnt, that;
        id = $this.attr('data-id');
        $item = DS.$("#" + _prefix + "-item-" + id);
        $count = isDel ? DS.$("#" + _prefix + "-item-count-" + id) : $this;
        count = isDel ? 0 : $count.val();
        parsedCnt = parseInt(count);
        that = this;
        if (!isDel && !parsedCnt && parsedCnt != count) {
          newCount = parsedCnt || 1;
          $count.val(newCount);
          parsedCnt = newCount;
        }
        DS.ajax('GET', DS.opts.host + 'shop_cart_lst.asp', {
          $el: $this,
          data: {
            cart_uid: DS.opts.cart_uid,
            product_id: id,
            product_cnt: parsedCnt
          },
          onLoad: function(res) {
            if (!res) {
              return false;
            }
            that.update(res, id);
          }
        });
      };

      return _Class;

    })()
  };

  DS.route = {
    home: {
      url: '/home',
      action: function() {
        DS.widget.category.mark();
        this.get();
      },
      get: function() {
        var that;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_products.asp', {
          $el: DS.widget.main.$el,
          data: {
            seller_id: DS.opts.seller_id,
            category_id: 0,
            rows: 10,
            order: DS.opts.sort,
            currency: DS.opts.currency
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
            DS.util.scrollUp();
          }
        });
      },
      render: function(data) {
        var articles, out, tmpl;
        out = '';
        articles = data.product;
        if (articles && articles.length) {
          tmpl = DS.tmpl(DS.tmpls['article' + DS.opts.main_view.charAt(0).toUpperCase() + DS.opts.main_view.slice(1)]);
          DS.util.each(articles, function(article) {
            out += tmpl({
              d: article,
              url: DS.opts.hashPrefix + ("/detail/" + article.id),
              imgsize: DS.opts.main_view === 'tile' ? DS.opts.imgsize_firstpage : DS.opts.imgsize_listpage
            });
          });
        }
        DS.widget.main.$el.html(DS.tmpl(DS.tmpls.showcaseArticles, {
          out: DS.opts.main_view === 'table' ? '<table class="digiseller-table">' + out + '</table>' : out,
          categories: data.categories
        }));
      }
    },
    search: {
      url: '/search(?:/([0-9]*))?\\?s=(.*)',
      search: null,
      page: null,
      rows: null,
      pager: null,
      prefix: 'digiseller-search',
      action: function(params) {
        this.search = decodeURIComponent(params[2]);
        this.page = parseInt(params[1]) || 1;
        this.rows = DS.opts.rows;
        DS.widget.category.mark();
        DS.widget.search.$input.val(this.search);
        this.get();
      },
      get: function() {
        var that;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_search.asp', {
          $el: DS.widget.main.$el,
          data: {
            seller_id: DS.opts.seller_id,
            currency: DS.opts.currency,
            page: this.page,
            rows: this.rows,
            search: this.search
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
            DS.util.scrollUp();
          }
        });
      },
      render: function(data) {
        var $container, articles, out, that, tmpl;
        out = '';
        articles = data.product;
        if (!articles || !articles.length) {
          out = DS.tmpl(DS.tmpls.nothing, {});
        } else {
          tmpl = DS.tmpl(DS.tmpls.searchResult);
          DS.util.each(articles, function(article) {
            out += tmpl({
              url: DS.opts.hashPrefix + ("/detail/" + article.id),
              d: article
            });
          });
        }
        $container = DS.$("#" + this.prefix + "-results");
        if ($container.length) {
          $container.html(out);
          this.pager.page = this.page;
          this.pager.rows = this.rows;
          this.pager.total = data.totalPages;
          this.pager.render();
        } else {
          DS.widget.main.$el.html(DS.tmpl(DS.tmpls.searchResults, {
            totalItems: data.totalItems,
            out: out
          }));
          that = this;
          tmpl = DS.tmpl(DS.tmpls.page);
          this.pager = new DS.widget.pager(DS.$('.digiseller-paging', DS.widget.main.$el), {
            page: this.page,
            rows: this.rows,
            total: data.totalPages,
            getLink: function(page) {
              return tmpl({
                page: page,
                url: DS.opts.hashPrefix + ("/search/" + page + "?s=" + that.search)
              });
            },
            onChangeRows: function(rows) {
              DS.opts.rows = rows;
              DS.cookie.set(DS.route.articles.prefix + '-rows', rows);
              that.page = 1;
              that.rows = rows;
              that.get();
              DS.historyClick.changeHashSilent(DS.opts.hashPrefix + ("/search/1?s=" + that.search));
            }
          }).render();
          DS.widget.currency.init();
        }
        DS.$("#" + this.prefix + "-query").html(this.search.replace('<', '&lt;').replace('>', '&gt;'));
        DS.$("#" + this.prefix + "-total").html(data.totalItems);
      }
    },
    articles: {
      url: '/articles/([0-9]*)(?:/([0-9]*))?',
      cid: null,
      page: 1,
      rows: null,
      pager: null,
      pagerComments: null,
      prefix: 'digiseller-articles',
      action: function(params) {
        this.cid = params[1];
        this.page = parseInt(params[2]) || 1;
        this.rows = DS.opts.rows;
        this.get();
      },
      get: function() {
        var that;
        DS.widget.category.mark(this.cid);
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_products.asp', {
          $el: DS.widget.main.$el,
          data: {
            seller_id: DS.opts.seller_id,
            category_id: this.cid,
            page: this.page,
            rows: this.rows,
            order: DS.opts.sort,
            currency: DS.opts.currency
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
            DS.util.scrollUp();
          }
        });
      },
      render: function(data) {
        var $container, articles, out, set, that, tmpl;
        out = '';
        data.totalPages = parseInt(data.totalPages);
        articles = data.product;
        if (!articles || !articles.length) {
          out = DS.tmpl(DS.tmpls.nothing, {});
        } else {
          tmpl = DS.tmpl(DS.tmpls['article' + DS.opts.view.charAt(0).toUpperCase() + DS.opts.view.slice(1)]);
          DS.util.each(articles, function(article) {
            out += tmpl({
              d: article,
              url: DS.opts.hashPrefix + ("/detail/" + article.id),
              imgsize: DS.opts.view === 'tile' ? DS.opts.imgsize_firstpage : DS.opts.imgsize_listpage
            });
          });
        }
        $container = DS.$("#" + this.prefix + "-" + this.cid);
        if ($container.length) {
          $container.html(DS.opts.view === 'table' ? '<table class="digiseller-table">' + out + '</table>' : out);
          this.pager.page = this.page;
          this.pager.rows = this.rows;
          this.pager.total = data.totalPages;
          this.pager.render();
        } else {
          DS.widget.main.$el.html(DS.tmpl(DS.tmpls.articles, {
            id: this.prefix + '-' + this.cid,
            d: data,
            hasCategories: !data.categories || !data.categories.length ? false : true,
            articlesPanel: data.totalPages ? DS.tmpl(DS.tmpls.articlesPanel, {}) : '',
            out: out
          }));
          if (data.totalPages) {
            that = this;
            tmpl = DS.tmpl(DS.tmpls.page);
            this.pager = new DS.widget.pager(DS.$('.digiseller-paging', DS.widget.main.$el), {
              page: this.page,
              rows: this.rows,
              total: data.totalPages,
              getLink: function(page) {
                return tmpl({
                  page: page,
                  url: DS.opts.hashPrefix + ("/articles/" + that.cid + "/" + page)
                });
              },
              onChangeRows: function(rows) {
                DS.opts.rows = rows;
                DS.cookie.set(that.prefix + '-rows', rows);
                that.page = 1;
                that.rows = rows;
                that.get();
                DS.historyClick.changeHashSilent(DS.opts.hashPrefix + ("/articles/" + that.cid + "/1"));
              }
            }).render();
            DS.widget.currency.init();
            set = function(param) {
              var $select;
              $select = DS.$("#digiseller-" + param + " select");
              $select.on('change', function(e) {
                DS.opts[param] = $select.val();
                DS.cookie.set(that.prefix + ("-" + param), DS.opts[param]);
                that.get();
              }).val(DS.opts[param]);
            };
            DS.util.each(['sort', 'view'], function(param) {
              set(param);
            });
          }
        }
      }
    },
    article: {
      url: '/detail(?:/([0-9]*))',
      comments: null,
      id: null,
      prefix: 'digiseller-article',
      action: function(params) {
        var that;
        this.id = params[1] || 0;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_product_info.asp', {
          $el: DS.widget.main.$el,
          data: {
            seller_id: DS.opts.seller_id,
            product_id: this.id,
            currency: DS.opts.currency
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
            DS.util.scrollUp();
          }
        });
      },
      render: function(data) {
        var $container, $preview, $thumbs, activeClass, onClick, that;
        if (!data || !data.product) {
          DS.widget.main.$el.html(DS.tmpl(DS.tmpls.nothing, {}));
          return;
        }
        DS.widget.category.mark(data.product.category_id);
        DS.widget.main.$el.html(DS.tmpl(DS.tmpls.articleDetail, {
          d: data.product,
          buy: DS.tmpl(DS.tmpls.buy, {
            d: data.product,
            failPage: DS.util.enc(window.location),
            agree: DS.opts.agree
          })
        }));
        new DS.widget.calc(data.product.id, data.product.prices_unit);
        DS.widget.currency.init();
        that = this;
        $container = DS.$("#" + this.prefix + "-thumbs");
        if ($container.length) {
          $thumbs = DS.$('a', $container);
          $preview = DS.$("#" + this.prefix + "-img-preview");
          activeClass = 'digiseller-left-thumbs-active';
          onClick = function($el) {
            var $next, $prev, id, index, type;
            type = $el.attr('data-type');
            index = parseInt($el.attr('data-index'));
            id = type === 'img' ? $el.attr('href') : $el.attr('data-id');
            $prev = $thumbs.eq(index - 1);
            $next = $thumbs.eq(index + 1);
            DS.popup.open(type, (type === 'img' ? id : DS.tmpl(DS.tmpls.video, {
              id: id,
              type: type
            })), $prev.length ? function() {
              onClick($prev);
            } : false, $next.length ? function() {
              onClick($next);
            } : false);
          };
          $thumbs.on('click', function(e) {
            DS.util.prevent(e);
            onClick(DS.$(this));
          }).on('mouseover', function(e) {
            var $this, id, index;
            $this = DS.$(this);
            if ($this.attr('data-type') !== 'img') {
              return;
            }
            $thumbs.removeClass(activeClass, true);
            $this.addClass(activeClass);
            index = $this.attr('data-index');
            id = $this.attr('data-id');
            $preview.attr('data-index', index).css('backgroundImage', $preview.css('backgroundImage').replace(/idp=[0-9]+&/, "idp=" + id + "&"));
          });
          $preview.on('click', function(e) {
            var index;
            DS.util.prevent(e);
            index = parseInt($preview.attr('data-index'));
            onClick($thumbs.eq(index));
          });
        }
      },
      initComments: function(callback) {
        var $el, rowsCookie, that;
        $el = DS.$("#" + this.prefix + "-comments-" + this.id);
        if ($el.attr('data-inited')) {
          if (callback) {
            callback();
          }
          return;
        }
        that = this;
        rowsCookie = 'digiseller-comments-rows';
        this.comments = new DS.widget.comments($el, this.id, function(data) {
          var tmpl;
          $el.attr('data-inited', 1);
          that.comments.$el.html(DS.tmpl(DS.tmpls.comments, {
            totalGood: data.totalGood,
            totalBad: data.totalBad
          }));
          if (callback) {
            callback();
          }
          DS.$('select', $el).on('change', function(e) {
            var $this;
            $this = DS.$(this);
            that.comments.page = 1;
            that.comments.type = DS.$('option', $this).eq(this.selectedIndex).val();
            that.comments.get();
          });
          tmpl = DS.tmpl(DS.tmpls.pageComment);
          that.comments.pager = new DS.widget.pager(DS.$('.digiseller-paging', that.comments.$el), {
            page: that.comments.page,
            rows: that.comments.rows,
            total: data.totalPages,
            getLink: function(page) {
              return tmpl({
                page: page,
                url: '#'
              });
            },
            onChangeRows: function(rows) {
              DS.cookie.set(rowsCookie, rows);
              that.comments.page = 1;
              that.comments.rows = rows;
              that.comments.get();
            }
          }).render();
        });
        this.comments.rows = DS.cookie.get(rowsCookie) || 10;
        this.comments.get();
      }
    },
    reviews: {
      url: '/reviews(?:/([0-9]*))?',
      comments: null,
      id: "",
      prefix: 'digiseller-reviews',
      action: function(params) {
        var that;
        if (!this.id || DS.$('#' + this.id).length === 0) {
          this.id = this.prefix + ("-" + (DS.util.getUID()));
          that = this;
          this.comments = new DS.widget.comments(DS.widget.main.$el, '', function(data) {
            that.initComments(data);
            DS.util.scrollUp();
          });
        }
        this.comments.page = parseInt(params[1]) || 1;
        this.comments.rows = DS.cookie.get(this.prefix + '-rows') || 10;
        this.comments.get();
      },
      initComments: function(data) {
        var $select, goToFirstPage, that, tmpl;
        this.comments.$el.html(DS.tmpl(DS.tmpls.reviews, {
          id: this.id,
          totalGood: data.totalGood,
          totalBad: data.totalBad
        }));
        that = this;
        tmpl = DS.tmpl(DS.tmpls.pageReview);
        goToFirstPage = function() {
          DS.historyClick.changeHashSilent(DS.opts.hashPrefix + "/reviews/1");
        };
        this.comments.pager = new DS.widget.pager(DS.$('.digiseller-paging', this.comments.$el), {
          page: this.comments.page,
          rows: this.comments.rows,
          total: data.totalPages,
          getLink: function(page) {
            return tmpl({
              page: page,
              url: DS.opts.hashPrefix + ("/reviews/" + page)
            });
          },
          onChangeRows: function(rows) {
            DS.cookie.set(that.prefix + '-rows', rows);
            that.comments.page = 1;
            that.comments.rows = rows;
            that.comments.get();
            goToFirstPage();
          }
        }).render();
        $select = DS.$("#" + this.prefix + "-type select");
        $select.on('change', function(e) {
          that.comments.page = 1;
          that.comments.type = $select.val();
          that.comments.get();
          goToFirstPage();
        });
      }
    },
    contacts: {
      url: '/contacts',
      action: function(params) {
        var that;
        that = this;
        DS.ajax('GET', DS.opts.host + 'shop_contacts.asp', {
          $el: DS.widget.main.$el,
          data: {
            seller_id: DS.opts.seller_id
          },
          onLoad: function(data) {
            if (!data) {
              return false;
            }
            DS.widget.main.$el.html(DS.tmpl(DS.tmpls.contacts, {
              d: data
            }));
            DS.util.scrollUp();
          }
        });
      }
    }
  };

  DS.eventsDisp = {
    'click-comments-page': function($el, e) {
      var page;
      DS.util.prevent(e);
      page = $el.attr('data-page');
      DS.route.article.comments.page = page;
      DS.route.article.comments.get();
    },
    'click-buy': function($el, e) {
      var $error, $form, $parent, $rules, ai, buy, data, error, id, isCart, isChecked, isForm, name, prefixBuy, prefixCalc, required$Els;
      DS.util.prevent(e);
      id = $el.attr('data-id');
      isForm = parseInt($el.attr('data-form'));
      isCart = parseInt($el.attr('data-cart'));
      prefixBuy = 'digiseller-buy';
      prefixCalc = 'digiseller-calc';
      if (isForm) {
        $form = DS.$("#" + prefixBuy + "-form-" + id);
        $error = DS.$("#" + prefixBuy + "-error-" + id);
        $rules = DS.$("#" + prefixCalc + "-rules");
        if ($rules.length) {
          isChecked = $rules.get(0).checked;
          DS.opts.agree = isChecked ? 1 : 0;
          DS.cookie.set('digiseller-agree', DS.opts.agree);
          if (!isChecked) {
            return;
          }
        }
        required$Els = {};
        data = DS.serialize($form.get(0), function(el) {
          var $parent;
          $parent = DS.$(el).parent();
          if ($parent.attr('data-required')) {
            return required$Els[el.name] = $parent;
          }
        });
        error = false;
        DS.$("." + prefixCalc + "-line", $form).removeClass(prefixCalc + '-line-err');
        for (name in required$Els) {
          $parent = required$Els[name];
          if (!DS.util.hasOwnProp(required$Els, name)) {
            continue;
          }
          if (!data[name]) {
            error = true;
            $parent.addClass(prefixCalc + '-line-err');
          }
        }
        $error.html(error ? DS.opts.i18n['someFieldsRequired'] : '');
        $error[error ? 'show' : 'hide']();
        if (error) {
          return;
        }
        if (!isCart) {
          $form.get(0).submit();
        } else {
          data.cart_uid = DS.opts.cart_uid;
          DS.ajax('POST', DS.opts.host + 'shop_cart_add.asp', {
            data: data,
            onLoad: function(res, xhr) {
              if (res.cart_err && res.cart_err !== '') {
                $error.html(res.cart_err).show();
              }
              DS.opts.cart_uid = res.cart_uid || '';
              DS.cookie.set('digiseller-cart_uid', DS.opts.cart_uid);
              DS.widget.cartButton.setCount(res.cart_cnt);
              new DS.widget.cart();
            }
          });
        }
      } else {
        ai = $el.attr('data-ai');
        buy = function() {
          window.open("https://www.oplata.info/asp/pay_x20.asp?id_d=" + id + "&ai=" + ai + "&dsn=limit", '_blank');
        };
        if (DS.opts.agreement_text) {
          DS.popup.open('text', DS.tmpl(DS.tmpls.agreement, {}));
          DS.$('#digiseller-agree').on('click', function() {
            DS.agree(true, buy);
          });
          DS.$('#digiseller-disagree').on('click', function() {
            DS.agree(false);
          });
        } else {
          buy();
        }
      }
    },
    'click-article-tab': function($el, e) {
      var $panels, change, index;
      DS.util.prevent(e);
      index = $el.attr('data-tab');
      $panels = $el.parent().next().children();
      $el.parent().children().removeClass('digiseller-activeTab');
      $el.addClass('digiseller-activeTab');
      change = function() {
        $panels.hide().eq(index).show();
      };
      if (index === '2') {
        DS.route.article.initComments(change);
      } else {
        change();
      }
    },
    'click-share': function($el, e) {
      var img, title, type;
      type = $el.attr('data-type');
      title = $el.attr('data-title');
      img = $el.attr('data-img');
      if (DS.share[type]) {
        window.open(DS.share[type](title, img), "digisellerShare_" + type, DS.util.getPopupParams(626, 436));
      }
    },
    'click-agreement': function($el, e) {
      DS.util.prevent(e);
      DS.popup.open('text', DS.tmpl(DS.tmpls.agreement, {}));
      DS.$('#digiseller-agree').on('click', function() {
        DS.agree(true);
      });
      DS.$('#digiseller-disagree').on('click', function() {
        DS.agree(false);
      });
    }
  };

  DS.inited = false;

  DS.init = function() {
    var getEl, homeInited, name, route, _fn, _ref;
    if (DS.inited) {
      return false;
    }
    DS.inited = true;
    getEl = function(elName) {
      return document.getElementsByTagName(elName)[0] || document.documentElement;
    };
    DS.el.head = getEl('html');
    DS.el.body = getEl('body');
    if (!DS.$('#digiseller-css').length) {
      DS.dom.getStyle(DS.opts.host + 'shop_css.asp?seller_id=' + DS.opts.seller_id);
    }
    DS.opts.currency = DS.cookie.get('digiseller-currency') || DS.opts.currency;
    DS.util.each(['sort', 'rows', 'view'], function(param) {
      DS.opts[param] = DS.cookie.get(DS.route.articles.prefix + '-' + param) || DS.opts[param];
    });
    DS.opts.agree = DS.cookie.get('digiseller-agree') || DS.opts.agree;
    DS.opts.cart_uid = DS.cookie.get('digiseller-cart_uid') || DS.opts.cart_uid;
    DS.widget.category.init();
    DS.widget.main.init();
    DS.widget.loader.init();
    DS.widget.search.init();
    DS.widget.lang.init();
    DS.widget.cartButton.init();
    DS.$('#digiseller-logo').html(DS.tmpl(DS.tmpls.logo, {
      logo_img: DS.opts.logo_img
    }));
    DS.$('#digiseller-topmenu').html(DS.tmpl(DS.tmpls.topmenu, {}));
    if (!DS.widget.category.$el.length) {
      DS.widget.main.$el.addClass('digiseller-main-nocategory');
    }
    homeInited = false;
    DS.historyClick.addRoute('#.*', function(params) {
      if (homeInited) {
        return;
      }
      homeInited = true;
      DS.route.home.action();
    });
    _ref = DS.route;
    _fn = function(route) {
      DS.historyClick.addRoute(DS.opts.hashPrefix + route.url, function(params) {
        homeInited = true;
        route.action(params);
      });
    };
    for (name in _ref) {
      route = _ref[name];
      if (!DS.route.hasOwnProperty(name) || !route.url || !route.action) {
        continue;
      }
      _fn(route);
    }
    DS.historyClick.rootAlias(DS.opts.hashPrefix + '/home');
    DS.historyClick.start();
    if (window.location.hash === '') {
      DS.historyClick.reload();
    }
    DS.historyClick.onGo = function() {
      DS.popup.close();
    };
  };

  window.DigiSeller = DS;

  checkReady = function() {
    setTimeout(function() {
      if (document.readyState !== 'loading') {
        return DS.init();
      } else {
        return checkReady();
      }
    }, 1);
  };

  checkReady();

  return;

}).call(this);
