// Generated by CoffeeScript 1.6.1

/*
DigiSeller-ru-api
22.03.2013 (c) http://artod.ru
*/


(function() {

  (function(window, document) {
    var DS, inited;
    if (window.DigiSeller != null) {
      false;
    }
    DS = {};
    DS.$el = {
      head: null,
      body: null,
      widget: null
    };
    DS.opts = {
      host: 'http://shop.digiseller.ru/xml/',
      widgetId: 'digiseller-ru',
      loader: '/test/img/loader.gif',
      hashPrefix: '#!digiseller'
    };
    DS.util = {
      getUID: (function() {
        var id;
        id = 1;
        return function() {
          return id++;
        };
      })(),
      enc: function(t) {
        return encodeURIComponent(t);
      },
      prevent: function(e) {
        if (e.preventDefault) {
          e.preventDefault();
        } else {
          e.returnValue = false;
        }
      },
      extend: function(target, source, overwrite) {
        var key;
        for (key in source) {
          if (!source.hasOwnProperty(key)) {
            continue;
          }
          if (overwrite || typeof target[key] === 'object') {
            target[key] = source[key];
          }
        }
        return target;
      },
      getPopupParams: function(width, height) {
        var left, outerHeight, outerWidth, screenX, screenY, top;
        screenX = typeof window.screenX !== 'undefined' ? window.screenX : window.screenLeft;
        screenY = typeof window.screenY !== 'undefined' ? window.screenY : window.screenTop;
        outerWidth = typeof window.outerWidth !== 'undefined' ? window.outerWidth : document.body.clientWidth;
        outerHeight = typeof window.outerHeight !== 'undefined' ? window.outerHeight : document.body.clientHeight - 22;
        left = parseInt(screenX + ((outerWidth - width) / 2), 10);
        top = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
        return "scrollbars=1, resizable=1, menubar=0, left=" + left + ", top=" + top + ", width=" + width + ", height=" + height + ", toolbar=0, status=0";
      },
      cookie: {
        get: function(name) {
          var matches = document.cookie.match(new RegExp(
				  "(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"
				));

				return matches ? decodeURIComponent(matches[1]) : undefined;;
        },
        set: function(name, value, props) {
          props = props || {};

				var exp = props.expires;
				if (typeof exp == 'number' && exp) {
					var d = new Date();
					d.setTime(d.getTime() + exp * 1000);
					exp = props.expires = d;
				}

				if (exp && exp.toUTCString) {
					props.expires = exp.toUTCString();
				}

				value = DS.util.enc(value);

				var updatedCookie = name + '=' + value;
				for (var propName in props) {
					updatedCookie += '; ' + propName;
					var propValue = props[propName];
					if (propValue !== true) {
						updatedCookie += '=' + propValue;
					}
				}

				document.cookie = updatedCookie;;
        },
        del: function(name) {
          this.set(name, null, {
            expires: -1
          });
        }
      }
    };
    DS.dom = {
      $: function(selector, context, tagName) {
        var name, type;
        if (!selector) {
          return;
        }
        type = selector.substring(0, 1);
        name = selector.substring(1);
        switch (type) {
          case '#':
            return document.getElementById(name);
          case '.':
            tagName = tagName ? tagName : '*';
            if ( typeof document.getElementsByClassName !== 'function' ) {						
						for (
							var i = -1,
								results = [ ],
								finder = new RegExp('(?:^|\\s)' + name + '(?:\\s|$)'),
								a = context && context.getElementsByTagName && context.getElementsByTagName(tagName) || document.all || document.getElementsByTagName(tagName),
								l = a.length;
							++i < l;
							finder.test(a[i].className) && results.push(a[i])
						);

						a = null;

						return results;
					} else {
						return (context || document).getElementsByClassName(name);
					};
            break;
          default:
            return (context || document).getElementsByTagName(selector);
        }
      },
      attr: function($el, attr, val) {
        if (!$el || typeof attr === 'undefined') {
          return false;
        }
        if (typeof val !== 'undefined') {
          $el.setAttribute(attr, val);
        } else {
          try {
            return $el.getAttribute(attr);
          } catch (e) {
            return null;
          }
        }
      },
      addEvent: function($el, e, callback) {
        var ieCallback;
        if ($el.attachEvent) {
          ieCallback = function(e) {
            return callback.call($el, e);
          };
          $el.attachEvent('on' + e, ieCallback);
          return ieCallback;
        } else if ($el.addEventListener) {
          $el.addEventListener(e, callback, false);
          return callback;
        }
      },
      removeEvent: function($el, e, callback) {
        if ($el.detachEvent) {
          $el.detachEvent("on" + type, callback);
        } else if ($el.removeEventListener) {
          $el.removeEventListener(e, callback, false);
        }
      },
      klass: function(action, els, c, multy) {
        if (!els || !action) {
				return;
			}

			if (!multy) {
				els = [els];
			}

			var $el, _i, _len,
				re = new RegExp('(^|\\s)' + ( action === 'add' ? c : c.replace(' ', '|') ) + '(\\s|$)', 'g');
			for (_len = els.length, _i = _len-1; _i >= 0; _i--) {
				$el = els[_i];
				if ( action === 'add' && re.test($el.className) ) {
					continue;
				}

				$el.className = action === 'add' ? ($el.className + ' ' + c).replace(/\s+/g, ' ').replace(/(^ | $)/g, '') : $el.className.replace(re, "$1").replace(/\s+/g, " ").replace(/(^ | $)/g, "");
			}

			return els;;
      },
      select: function($select, val) {
        var $option, $options, i, _i, _len;
        $options = DS.dom.$('option', $select);
        for (i = _i = 0, _len = $options.length; _i < _len; i = ++_i) {
          $option = $options[i];
          if ($option.value === val + '') {
            $select.selectedIndex = i;
            return;
          }
        }
      },
      getStyle: function(url, onLoad) {
        var css, link;
        link = document.createElement('link');
        link.type = 'text/css';
        link.rel = 'stylesheet';
        link.href = url;
        DS.$el.head.appendChild(link);
        css = new Image();
        css.onerror = function() {
          if (onLoad) {
            return onLoad();
          }
        };
        css.src = url;
      },
      getScript: function(url, onLoad, onError) {
        var done, onComplite, script;
        script = document.createElement('script');
        script.type = 'text/javascript';
        script.setAttribute('encoding', 'UTF-8');
        script.src = url;
        done = false;
        onComplite = function(e) {
          DS.widget.loader.hide();
          done = true;
          script.onload = script.onreadystatechange = null;
          if (DS.$el.head && script.parentNode) {
            DS.$el.head.removeChild(script);
          }
        };
        script.onload = script.onreadystatechange = function(e) {
          if (!done && (!this.readyState || this.readyState === 'loaded' || this.readyState === 'complete')) {
            onComplite();
            if (onLoad != null) {
              onLoad();
            }
          }
        };
        script.onerror = function(e) {
          onComplite();
          if (onError != null) {
            onError;
          }
        };
        DS.widget.loader.show();
        DS.$el.head.appendChild(script);
      }
    };
    DS.widget = {
      main: {
        $el: null
      },
      loader: {
        $el: null,
        timeout: null,
        show: function() {
          var that;
          if (!this.$el) {
            return;
          }
          that = this;
          clearTimeout(this.timeout);
          this.timeout = setTimeout(function() {
            return that.$el.style.display = '';
          }, 1000);
        },
        hide: function() {
          if (!this.$el) {
            return;
          }
          clearTimeout(this.timeout);
          this.$el.style.display = 'none';
        }
      },
      currency: {
        $el: null,
        init: function() {
          var $sel;
          this.$el = DS.dom.$('#digiseller-currency');
          this.$el.innerHTML = DS.tmpls.currency;
          $sel = DS.dom.$('select', this.$el)[0];
          DS.dom.addEvent($sel, 'change', function(e) {
            var type;
            type = DS.dom.attr(this, 'data-type');
            DS.opts.currency = DS.dom.$('option', this)[this.selectedIndex].value;
            DS.util.cookie.set("digiseller-currency", DS.opts.currency);
            DS.historyClick.reload();
          });
          DS.dom.select($sel, DS.opts.currency);
        }
      },
      search: {
        $el: null,
        $input: null,
        init: function($el) {
          var form, that;
          this.$el = $el;
          this.$input = DS.dom.$('.digiseller-search-input', this.$el, 'input')[0];
          form = DS.dom.$('.digiseller-search-form', this.$el, 'form')[0];
          that = this;
          DS.dom.addEvent(form, 'submit', function(e) {
            DS.util.prevent(e);
            window.location.hash = DS.opts.hashPrefix + ("/search?s=" + that.$input.value);
          });
        }
      },
      pager: (function() {

        function _Class($el, opts) {
          this.$el = $el;
          opts = opts || {};
          this.page = opts.page || 1;
          this.rows = opts.rows || 10;
          this.total = opts.total || 0;
          this.opts = {
            tmpl: opts.tmpl || DS.tmpls.pages,
            max: opts.max || 2,
            getLink: opts.getLink || function(page) {
              return page;
            },
            onChangeRows: opts.onChangeRows || function(rows) {}
          };
          return;
        }

        _Class.prototype.mark = function() {
          var index, page, pages, _i, _len;
          pages = DS.dom.$('a', this.$el);
          for (index = _i = 0, _len = pages.length; _i < _len; index = ++_i) {
            page = pages[index];
            DS.dom.klass((this.page === parseInt(DS.dom.attr(page, 'data-page')) ? 'add' : 'remove'), page, 'digiseller-activepage');
          }
          return this;
        };

        _Class.prototype.render = function() {
          var $select, left, out, page, right, that;
          this.page = parseInt(this.page);
          this.rows = parseInt(this.rows);
          this.total = parseInt(this.total);
          this.$el.style.display = this.total ? '' : 'none';
          left = this.page - this.opts.max;
          left = left < 1 ? 1 : left;
          right = this.page + this.opts.max;
          right = right > this.total ? this.total : right;
          page = left;
          out = '';
          while (page <= right) {
            out += this.opts.getLink(page);
            page++;
          }
          if (left > 1) {
            out = this.opts.getLink(1) + (left > 2 ? '<span>...</span>&nbsp;' : '') + out;
          }
          if (right < this.total) {
            out = out + (right < this.total - 1 ? '<span>...</span>&nbsp;' : '') + this.opts.getLink(this.total);
          }
          this.$el.innerHTML = DS.tmpl(this.opts.tmpl, {
            out: out
          });
          that = this;
          $select = DS.dom.$('select', this.$el)[0];
          DS.dom.addEvent($select, 'change', function(e) {
            that.rows = DS.dom.$('option', this)[this.selectedIndex].value;
            return that.opts.onChangeRows(that.rows);
          });
          DS.dom.select($select, this.rows);
          this.mark();
          return this;
        };

        return _Class;

      })(),
      comments: (function() {

        function _Class($el, product_id, init) {
          this.$el = $el;
          this.product_id = product_id;
          this.init = init;
          this.isInited = false;
          this.type = '';
          this.page = 1;
          this.rows = 10;
          this.pager = null;
          return;
        }

        _Class.prototype.get = function() {
          var that;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_reviews.asp', this.$el, {
            seller_id: DS.opts.seller_id,
            product_id: this.product_id,
            format: 'json',
            type: this.type,
            page: this.page,
            rows: this.rows
          }, function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          });
        };

        _Class.prototype.render = function(data) {
          var comment, comments, out, _i, _len;
          comments = data.review;
          out = '';
          if (!comments) {
            out = DS.tmpls.nothing;
          } else {
            for (_i = 0, _len = comments.length; _i < _len; _i++) {
              comment = comments[_i];
              out += DS.tmpl(DS.tmpls.comment, {
                d: comment
              });
            }
          }
          if (this.isInited) {
            this.pager.page = this.page;
            this.pager.rows = this.rows;
            this.pager.total = data.totalPages;
            this.pager.render();
          } else {
            this.init(data);
            this.container = DS.dom.$('.digiseller-comments', this.$el)[0];
            this.isInited = true;
          }
          this.container.innerHTML = out;
        };

        return _Class;

      })(),
      category: {
        $el: null,
        isInited: false,
        init: function($el) {
          var that;
          this.$el = $el;
          this.isInited = false;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_categories.asp', this.$el, {
            seller_id: DS.opts.seller_id,
            format: 'json'
          }, function(data) {
            if (!data) {
              return false;
            }
            that.$el.innerHTML = that.render(data.category);
            that.isInited = true;
            that.mark();
          });
        },
        mark: (function() {
          var go;
          go = function(cid) {
            var cat, cats, parent, sub, subs, _i, _len, _ref;
            cats = DS.dom.$('li', this.$el);
            if (!cats.length) {
              return;
            }
            subs = DS.dom.$('ul', this.$el);
            for (_i = 0, _len = subs.length; _i < _len; _i++) {
              sub = subs[_i];
              sub.style.display = 'none';
            }
            subs[0].style.display = '';
            DS.dom.klass('remove', cats, 'digiseller-activecat', true);
            if (!cid) {
              return;
            }
            cat = DS.dom.$("#digiseller-category-" + cid);
            if (!cat) {
              return;
            }
            DS.dom.klass('add', cat, 'digiseller-activecat');
            parent = cat;
            while (parent.id !== 'digiseller-category') {
              parent.style.display = '';
              parent = parent.parentNode;
            }
            if ((_ref = DS.dom.$("#digiseller-category-sub-" + cid)) != null) {
              _ref.style.display = '';
            }
          };
          return function(cid) {
            var count, interval, that;
            if (this.isInited) {
              go.call(this, cid);
            } else {
              that = this;
              count = 0;
              interval = setInterval(function() {
                if (that.isInited || count > 1000) {
                  clearInterval(interval);
                  if (that.isInited) {
                    go.call(that, cid);
                  }
                }
                count++;
              }, 50);
            }
          };
        })(),
        render: function(categories, parent_cid) {
          var category, out, _i, _len;
          if (!categories) {
            return '';
          }
          out = '';
          for (_i = 0, _len = categories.length; _i < _len; _i++) {
            category = categories[_i];
            out += DS.tmpl(DS.tmpls.category, {
              d: category,
              url: DS.opts.hashPrefix + ("/articles/" + category.id),
              id: "digiseller-category-" + category.id,
              sub: this.render(category.sub, category.id)
            });
          }
          return DS.tmpl(DS.tmpls.categories, {
            id: parent_cid ? "digiseller-category-sub-" + parent_cid : '',
            out: out
          });
        }
      }
    };
    DS.route = {
      home: {
        url: '/home',
        action: function(params) {
          DS.widget.category.mark();
          this.get();
        },
        get: function() {
          var that;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_products.asp', DS.widget.main.$el, {
            seller_id: DS.opts.seller_id,
            category_id: 0,
            rows: 10,
            format: 'json',
            order: DS.opts.sort,
            currency: DS.opts.currency
          }, function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          });
        },
        render: function(data) {
          var article, articles, out, _i, _len;
          out = '';
          articles = data.product;
          if (articles && articles.length) {
            for (_i = 0, _len = articles.length; _i < _len; _i++) {
              article = articles[_i];
              out += DS.tmpl(DS.tmpls.showcaseArticle, {
                d: article,
                url: DS.opts.hashPrefix + ("/detail/" + article.id),
                imgsize: DS.opts.imgsize_firstpage
              });
            }
          }
          return DS.widget.main.$el.innerHTML = DS.tmpl(DS.tmpls.showcaseArticles, {
            out: out
          });
        }
      },
      search: {
        url: '/search(?:/([0-9]*))?\\?s=(.*)',
        search: null,
        page: null,
        rows: null,
        pager: null,
        action: function(params) {
          this.search = decodeURIComponent(params[2]);
          this.page = parseInt(params[1]) || 1;
          this.rows = DS.opts.rows;
          DS.widget.category.mark();
          DS.widget.search.$input.value = this.search;
          this.get();
        },
        get: function() {
          var that;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_search.asp', DS.widget.main.$el, {
            seller_id: DS.opts.seller_id,
            format: 'json',
            currency: DS.opts.currency,
            page: this.page,
            rows: this.rows,
            search: this.search
          }, function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          });
        },
        render: function(data) {
          var article, articles, container, out, that, _i, _len;
          out = '';
          articles = data.product;
          if (!articles || !articles.length) {
            out = DS.tmpls.nothing;
          } else {
            for (_i = 0, _len = articles.length; _i < _len; _i++) {
              article = articles[_i];
              out += DS.tmpl(DS.tmpls.searchResult, {
                url: DS.opts.hashPrefix + ("/detail/" + article.id),
                imgsize: DS.opts.imgsize_listpage,
                d: article
              });
            }
          }
          container = DS.dom.$('#digiseller-search-results');
          if (container) {
            container.innerHTML = out;
            this.pager.page = this.page;
            this.pager.rows = this.rows;
            this.pager.total = data.totalPages;
            this.pager.render();
          } else {
            DS.widget.main.$el.innerHTML = DS.tmpl(DS.tmpls.searchResults, {
              totalItems: data.totalItems,
              out: out
            });
            that = this;
            this.pager = new DS.widget.pager(DS.dom.$('.digiseller-paging', DS.widget.main.$el)[0], {
              page: this.page,
              rows: this.rows,
              total: data.totalPages,
              getLink: function(page) {
                return DS.tmpl(DS.tmpls.page, {
                  page: page,
                  url: DS.opts.hashPrefix + ("/search/" + page + "?s=" + that.search)
                });
              },
              onChangeRows: function(rows) {
                DS.opts.rows = rows;
                DS.util.cookie.set('digiseller-articles-rows', rows);
                that.page = 1;
                that.rows = rows;
                that.get();
                DS.historyClick.changeHashSilent(DS.opts.hashPrefix + ("/search/1?s=" + that.search));
              }
            }).render();
            DS.widget.currency.init();
          }
          DS.dom.$('#digiseller-search-query').innerHTML = this.search.replace('<', '&lt;').replace('>', '&gt;');
          DS.dom.$('#digiseller-search-total').innerHTML = data.totalItems;
        }
      },
      articles: {
        url: '/articles/([0-9]*)(?:/([0-9]*))?',
        cid: null,
        page: 1,
        rows: null,
        pager: null,
        pagerComments: null,
        action: function(params) {
          this.cid = params[1];
          this.page = parseInt(params[2]) || 1;
          this.rows = DS.opts.rows;
          this.get();
        },
        get: function() {
          var that;
          DS.widget.category.mark(this.cid);
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_products.asp', DS.widget.main.$el, {
            seller_id: DS.opts.seller_id,
            format: 'json',
            category_id: this.cid,
            page: this.page,
            rows: this.rows,
            order: DS.opts.sort,
            currency: DS.opts.currency
          }, function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          });
        },
        render: function(data) {
          var $selectSort, article, articles, container, out, that, _i, _len;
          out = '';
          articles = data.product;
          if (!articles) {
            out = DS.tmpls.nothing;
          } else {
            for (_i = 0, _len = articles.length; _i < _len; _i++) {
              article = articles[_i];
              out += DS.tmpl(DS.tmpls.article, {
                d: article,
                url: DS.opts.hashPrefix + ("/detail/" + article.id),
                imgsize: DS.opts.imgsize_listpage
              });
            }
          }
          container = DS.dom.$("#digiseller-articles-" + this.cid);
          if (container) {
            container.innerHTML = out;
            this.pager.page = this.page;
            this.pager.rows = this.rows;
            this.pager.total = data.totalPages;
            this.pager.render();
          } else {
            DS.widget.main.$el.innerHTML = DS.tmpl(DS.tmpls.articles, {
              id: "digiseller-articles-" + this.cid,
              breadCrumbs: data.breadCrumbs,
              out: out
            });
            that = this;
            this.pager = new DS.widget.pager(DS.dom.$('.digiseller-articles-pager', DS.widget.main.$el)[0], {
              page: this.page,
              rows: this.rows,
              total: data.totalPages,
              getLink: function(page) {
                return DS.tmpl(DS.tmpls.page, {
                  page: page,
                  url: DS.opts.hashPrefix + ("/articles/" + that.cid + "/" + page)
                });
              },
              onChangeRows: function(rows) {
                DS.opts.rows = rows;
                DS.util.cookie.set('digiseller-articles-rows', rows);
                that.page = 1;
                that.rows = rows;
                that.get();
                DS.historyClick.changeHashSilent(DS.opts.hashPrefix + ("/articles/" + that.cid + "/1"));
              }
            }).render();
            DS.widget.currency.init();
            $selectSort = DS.dom.$('select', DS.dom.$('#digiseller-sort'))[0];
            DS.dom.addEvent($selectSort, 'change', function(e) {
              DS.opts.sort = DS.dom.$('option', this)[this.selectedIndex].value;
              DS.util.cookie.set('digiseller-articles-sort', DS.opts.sort);
              return that.get();
            });
            DS.dom.select($selectSort, DS.opts.sort);
          }
        }
      },
      article: {
        url: '/detail(?:/([0-9]*))',
        comments: null,
        id: null,
        action: function(params) {
          var that;
          this.id = params[1] || 0;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_product_info.asp', DS.widget.main.$el, {
            seller_id: DS.opts.seller_id,
            format: 'json',
            product_id: this.id,
            currency: DS.opts.currency
          }, function(data) {
            if (!data) {
              return false;
            }
            that.render(data);
          });
        },
        render: function(data) {
          var $thumb, $thumbs, _i, _len, _ref;
          if (!data || !data.product) {
            DS.widget.main.$el.innerHTML = DS.tmpls.nothing;
            return;
          }
          DS.widget.category.mark(data.product.category_id);
          DS.widget.main.$el.innerHTML = DS.tmpl(DS.tmpls.articleDetail, {
            d: data.product,
            imgsize: DS.opts.imgsize_infopage
          });
          DS.widget.currency.init();
          $thumbs = DS.dom.$('#digiseller-article-thumbs');
          if ($thumbs && $thumbs.children) {
            _ref = $thumbs.children;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              $thumb = _ref[_i];
              DS.dom.addEvent($thumb, 'click', function(e) {
                var $el, $preview, $previewImg, height, id, orig, width;
                $el = this;
                if (DS.dom.attr($el, 'class') === 'digiseller-videothumb') {
                  return;
                }
                DS.util.prevent(e);
                orig = DS.dom.attr($el, 'href');
                id = DS.dom.attr($el, 'data-id');
                height = parseInt(DS.dom.attr($el, 'data-height'));
                width = parseInt(DS.dom.attr($el, 'data-width'));
                $preview = DS.dom.$('#digiseller-img-preview');
                $previewImg = DS.dom.$('img', $preview)[0];
                $preview.href = orig;
                $previewImg.src = $previewImg.src.replace(/idp=[0-9]+&(h|w)/i, "idp=" + id + "&" + (height > width ? 'h' : 'w'));
              });
            }
          }
        },
        initComments: function() {
          var $el, that;
          $el = DS.dom.$('#digiseller-article-comments-' + this.id);
          if (DS.dom.attr($el, 'inited')) {
            return;
          }
          that = this;
          this.comments = new DS.widget.comments($el, this.id, function(data) {
            var $selectType;
            DS.dom.attr($el, 'inited', 1);
            that.comments.$el.innerHTML = DS.tmpl(DS.tmpls.comments, {
              totalGood: data.totalGood,
              totalBad: data.totalBad
            });
            $selectType = DS.dom.$('select', $el)[0];
            DS.dom.addEvent($selectType, 'change', function(e) {
              that.comments.page = 1;
              that.comments.type = DS.dom.$('option', this)[this.selectedIndex].value;
              return that.comments.get();
            });
            that.comments.pager = new DS.widget.pager(DS.dom.$('.digiseller-paging', that.comments.$el)[0], {
              page: that.comments.page,
              rows: that.comments.rows,
              total: data.totalPages,
              getLink: function(page) {
                return DS.tmpl(DS.tmpls.pageComment, {
                  page: page,
                  url: '#'
                });
              },
              onChangeRows: function(rows) {
                DS.util.cookie.set('digiseller-comments-rows', rows);
                that.comments.page = 1;
                that.comments.rows = rows;
                that.comments.get();
              }
            }).render();
          });
          this.comments.rows = DS.util.cookie.get('digiseller-comments-rows') || 10;
          this.comments.get();
        }
      },
      reviews: {
        url: '/reviews(?:/([0-9]*))?',
        comments: null,
        id: "",
        action: function(params) {
          var that;
          if (!DS.dom.$('#' + this.id)) {
            this.id = "digiseller-reviews-" + (DS.util.getUID());
            that = this;
            this.comments = new DS.widget.comments(DS.widget.main.$el, '', function(data) {
              return that.initComments(data);
            });
          }
          this.comments.page = parseInt(params[1]) || 1;
          this.comments.rows = DS.util.cookie.get('digiseller-reviews-rows') || 10;
          this.comments.get();
        },
        initComments: function(data) {
          var that;
          this.comments.$el.innerHTML = DS.tmpl(DS.tmpls.reviews, {
            id: this.id,
            totalGood: data.totalGood,
            totalBad: data.totalBad
          });
          that = this;
          this.comments.pager = new DS.widget.pager(DS.dom.$('.digiseller-paging', this.comments.$el)[0], {
            page: this.comments.page,
            rows: this.comments.rows,
            total: data.totalPages,
            getLink: function(page) {
              return DS.tmpl(DS.tmpls.pageReview, {
                page: page,
                url: "#!digiseller/reviews/" + page
              });
            },
            onChangeRows: function(rows) {
              DS.util.cookie.set('digiseller-reviews-rows', rows);
              that.comments.page = 1;
              that.comments.rows = rows;
              that.comments.get();
            }
          }).render();
          DS.dom.addEvent(DS.dom.$('select', DS.dom.$('#digiseller-reviews-type'))[0], 'change', function(e) {
            that.comments.page = 1;
            that.comments.type = DS.dom.$('option', this)[this.selectedIndex].value;
            return that.comments.get();
          });
        }
      },
      contacts: {
        url: '/contacts',
        action: function(params) {
          var that;
          that = this;
          DS.JSONP.get(DS.opts.host + 'shop_contacts.asp', DS.widget.main.$el, {
            seller_id: DS.opts.seller_id,
            format: 'json'
          }, function(data) {
            if (!data) {
              false;
            }
            DS.widget.main.$el.innerHTML = DS.tmpl(DS.tmpls.contacts, {
              d: data
            });
          });
        }
      }
    };
    DS.events = {
      'click-comments-page': function($el, e) {
        var page;
        DS.util.prevent(e);
        page = DS.dom.attr($el, 'data-page');
        DS.route.article.comments.page = page;
        DS.route.article.comments.get();
      },
      'click-buy': function($el, e) {
        var id;
        DS.util.prevent(e);
        id = DS.dom.attr($el, 'data-id');
        window.open("https://www.oplata.info/asp/pay_x20.asp?id_d=" + id + "&dsn=limit", '_blank');
      },
      'click-article-tab': function($el, e) {
        var $panel, $panels, index, _i, _len;
        DS.util.prevent(e);
        index = DS.dom.attr($el, 'data-tab');
        $panels = $el.parentNode.nextSibling.children;
        DS.dom.klass('remove', $el.parentNode.children, 'digiseller-activeTab', true);
        DS.dom.klass('add', $el, 'digiseller-activeTab');
        for (_i = 0, _len = $panels.length; _i < _len; _i++) {
          $panel = $panels[_i];
          $panel.style.display = 'none';
        }
        $panels[index].style.display = '';
        if (index === '1') {
          DS.route.article.initComments();
        }
      },
      'click-share': function($el, e) {
        var img, title, type;
        type = DS.dom.attr($el, 'data-type');
        title = DS.dom.attr($el, 'data-title');
        img = DS.dom.attr($el, 'data-img');
        if (DS.share[type]) {
          return window.open(DS.share[type](title, img), "digisellerShare_" + type, DS.util.getPopupParams(626, 436));
        }
      }
    };
    inited = false;
    DS.init = function() {
      var callback;
      if (inited) {
        return false;
      }
      inited = true;
      DS.$el.head = DS.dom.$('head')[0] || document.documentElement;
      DS.$el.body = DS.dom.$('body')[0] || document.documentElement;
      DS.$el.shop = DS.dom.$("#" + DS.opts.widgetId);
      DS.dom.getStyle(DS.opts.host + 'shop_css.asp?seller_id=' + DS.opts.seller_id, function() {
        var name, route, _fn, _ref;
        DS.opts.currency = DS.util.cookie.get('digiseller-currency') || DS.opts.currency;
        DS.opts.sort = DS.util.cookie.get('digiseller-articles-sort') || DS.opts.sort;
        DS.opts.rows = DS.util.cookie.get('digiseller-articles-rows') || DS.opts.rows;
        DS.$el.shop.innerHTML = DS.tmpl(DS.tmpls.main, {
          d: DS.opts
        });
        DS.widget.main.$el = DS.dom.$('#digiseller-main');
        DS.widget.loader.$el = DS.dom.$('#digiseller-loader');
        DS.widget.category.init(DS.dom.$('#digiseller-category'));
        DS.widget.search.init(DS.dom.$('#digiseller-search'));
        _ref = DS.route;
        _fn = function(route) {
          DS.historyClick.addRoute(DS.opts.hashPrefix + route.url, function(params) {
            return route.action(params);
          });
        };
        for (name in _ref) {
          route = _ref[name];
          if (!(DS.route.hasOwnProperty(name) || route.url || route.action)) {
            continue;
          }
          _fn(route);
        }
        DS.historyClick.rootAlias(DS.opts.hashPrefix + '/home');
        DS.historyClick.start();
        if (window.location.hash === '') {
          DS.historyClick.reload();
        }
      });
      callback = function(e, type) {
        var $el, action;
        $el = e.originalTarget || e.srcElement;
        action = DS.dom.attr($el, 'data-action');
        if (action && typeof DS.events[type + '-' + action] === 'function') {
          return DS.events[type + '-' + action]($el, e);
        }
      };
      DS.dom.addEvent(DS.$el.shop, 'click', function(e) {
        return callback(e, 'click');
      });
    };
    DS.share = {
      vk: function(title, img) {
        return "//vkontakte.ru/share.php?url=" + (DS.util.enc(document.location)) + "&title=" + (DS.util.enc(title)) + "&image=" + (DS.util.enc(img)) + "&noparse=true";
      },
      tw: function(title) {
        return "//twitter.com/share?text=" + (DS.util.enc(title)) + "&url=" + (DS.util.enc(document.location));
      },
      fb: function(title, img) {
        return "//www.facebook.com/sharer.php?s=100&p[url]=" + (DS.util.enc(document.location)) + "&p[title]=" + (DS.util.enc(title)) + "&p[images][0]=" + (DS.util.enc(img));
      },
      wme: function(title, img) {
        return "//events.webmoney.ru/sharer.aspx?url=" + (DS.util.enc(document.location)) + "&title=" + (DS.util.enc(title)) + "&image=" + (DS.util.enc(img)) + "&noparse=0";
      }
    };
    DS.historyClick = (function() {
		var _rootAlias = '',
			_needReload = false,
			_routes = [],
			_revRoutes = [];

		function init() {
			if (!historyClick.interval) {
				historyClick.interval = setInterval(urlHashCheck, 100);
			}
		}

		function urlHashCheck() {
			var mayChangeReload = false; // _needReload может обнулиться так как urlHashCheck может еще не закончиться а _needReload уже поставили true

			if (_needReload) {
				mayChangeReload = true;
			}

			if (window.location.hash !== historyClick.currentHash || _needReload) {
				historyClick.prevHash = ( _needReload ? historyClick.prevHash : historyClick.currentHash );
				historyClick.currentHash = window.location.hash.toString();

				go(historyClick.currentHash && historyClick.currentHash != '#' ? historyClick.currentHash : _rootAlias);

				if (mayChangeReload) {
					_needReload = false;
				}
			}
		}

		function go(hash) {
			if (!hash) {
				return;
			}

			var pattern,
				callback;

			for (var i = 0, len = _revRoutes.length; i < len; i++) {
				pattern = _revRoutes[i][0];
				callback = _revRoutes[i][1];

				if (pattern.test(hash) && typeof callback === 'function') {
					historyClick.params = hash.match(pattern)
					callback(historyClick.params);

					return;
				}
			}
		}

		var historyClick = {
			interval: null,
			currentHash: '',
			prevHash: '',
			params: [],
			start: function() {
				init();
			},
			rootAlias: function(hash) {
				if (hash) {
					_rootAlias = hash;
				} else {
					return _rootAlias;
				}
			},
			addRoute: function(pattern, callback) {
				if (typeof pattern === 'string') {
					pattern = [pattern];
				}

				for (var i = 0; i < pattern.length; i++) {
					_routes.push([new RegExp(pattern[i], 'i'), callback]);
				}

				_revRoutes = _routes.slice().reverse(); // клонируем и реверсируем
			},
			reload: function() {
				_needReload = true;
			},
			changeHashSilent: function(hash) {
				historyClick.prevHash = historyClick.currentHash;
				historyClick.currentHash = window.location.hash = hash;
			}
		};

		return historyClick;
	})();;
    DS.JSONP = (function() {
		var _callbacks = [];

		function jsonp(url, el, params, callback) {
			var query = (url || '').indexOf('?') === -1 ? '?' : '&', key;

			params = params || {};

			var _uid = DS.util.getUID(); 
			params.queryId = _uid;

			for (key in params) {
				if ( !params.hasOwnProperty(key) ) {
					continue;
				}

				query += DS.util.enc(key) + '=' + DS.util.enc(params[key]) + '&'
			}			
			
			var needCheck = el ? true : false;
			
			if (needCheck) {				
				DS.dom.attr(el, 'data-qid', _uid);
			}
			
			_callbacks[_uid] = function(data) {
				if ( needCheck && ( !el || data.queryId != DS.dom.attr(el, 'data-qid') ) ) {
					return;
				}
				
				callback(data);
			};

			DS.dom.getScript( url + query + '_' + Math.random() );
			
			return _uid;
		}

		return {
			get: jsonp,
			callback: function(data) {
				if (!data || !data.queryId || !_callbacks[data.queryId]) {
					return;
				}
				
				_callbacks[data.queryId](data);

				try {
					delete _callbacks[data.queryId];
				} catch (e) {}

				_callbacks[data.queryId] = null;
			}
		};
	})();
    DS.tmpl = function(text, data) {
		settings = {
			evaluate		: /<\?([\s\S]+?)\?>/g,
			interpolate : /<\?=([\s\S]+?)\?>/g,
			escape			: /<\?-([\s\S]+?)\?>/g
		};

		// Combine delimiters into one regular expression via alternation.
		var noMatch = /(.)^/;
		var matcher = new RegExp([
			(settings.escape || noMatch).source,
			(settings.interpolate || noMatch).source,
			(settings.evaluate || noMatch).source
		].join('|') + '|$', 'g');

		// Compile the template source, escaping string literals appropriately.
		var index = 0,
			source = "__p+='",
			escaper = /\\|'|\r|\n|\t|\u2028|\u2029/g,
			escapes = {
				"'":			"'",
				'\\':		 '\\',
				'\r':		 'r',
				'\n':		 'n',
				'\t':		 't',
				'\u2028': 'u2028',
				'\u2029': 'u2029'
			};

		text.replace(matcher, function(match, escape, interpolate, evaluate, offset) {
			source += text.slice(index, offset)
				.replace(escaper, function(match) {
					return '\\' + escapes[match];
				});

			/* todo: _.escape переделать */
			source +=
				escape ? "'+\n((__t=(" + escape + "))==null?'':_.escape(__t))+\n'" :
				interpolate ? "'+\n((__t=(" + interpolate + "))==null?'':__t)+\n'" :
				evaluate ? "';\n" + evaluate + "\n__p+='" : '';

			index = offset + match.length;
		});

		source += "';\n";

		// If a variable is not specified, place data values in local scope.
		if (!settings.variable) {
			source = 'with(obj||{}){\n' + source + '}\n';
		}

		source = "var __t,__p='',__j=Array.prototype.join," +
			"print=function(){__p+=__j.call(arguments,'');};\n" +
			source + "return __p;\n";

		try {
			var render = new Function(settings.variable || 'obj', /*'_', */source);
		} catch (e) {
			e.source = source;
			throw e;
		}

		if (data) {
			return render(data/*, _*/);
		}

		var template = function(data) {
			return render.call(this, data/*, _*/);
		};

		// Provide the compiled function source as a convenience for precompilation.
		template.source = 'function(' + (settings.variable || 'obj') + '){\n' + source + '}';

		return template;
	};;
    window.DigiSeller = DS;
    DS.dom.addEvent(window, 'load', DS.init);
  })(window, document);

}).call(this);
